apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-bank
  namespace: api-platform-poc
  labels:
    app.kubernetes.io/name: mock-bank
    app.kubernetes.io/part-of: api-platform-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mock-bank
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mock-bank
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mock-bank
          image: api-platform/mock-bank:local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
---
apiVersion: v1
kind: Service
metadata:
  name: mock-bank
  namespace: api-platform-poc
  annotations:
    konghq.com/plugins: platform-key-auth,platform-rate-limit,platform-correlation-id,platform-request-transformer,platform-response-transformer,platform-prometheus
spec:
  selector:
    app.kubernetes.io/name: mock-bank
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mock-bank
  namespace: api-platform-poc
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mock-bank
