apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: platform-key-auth
  namespace: api-platform-poc
plugin: key-auth
config:
  key_names: [apikey]
  hide_credentials: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: platform-rate-limit
  namespace: api-platform-poc
plugin: rate-limiting
config:
  minute: 10
  policy: local
  fault_tolerant: false
  hide_client_headers: false
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: platform-correlation-id
  namespace: api-platform-poc
plugin: correlation-id
config:
  header_name: X-Correlation-ID
  generator: uuid
  echo_downstream: true
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: platform-request-transformer
  namespace: api-platform-poc
plugin: request-transformer
config:
  add:
    headers: ["X-API-Platform-Gateway:kong-poc"]
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: platform-response-transformer
  namespace: api-platform-poc
plugin: response-transformer
config:
  add:
    headers: ["X-API-Platform-PoC:synthetic-only"]
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: platform-prometheus
  namespace: api-platform-poc
plugin: prometheus
config:
  status_code_metrics: true
  latency_metrics: true
  upstream_health_metrics: true
