#!/usr/bin/env python3
"""Build the API Management Studies static site with Python's standard library."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import re
import shutil
import subprocess
import unicodedata
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SITE_SOURCE = ROOT / "site"
DEFAULT_OUTPUT = ROOT / "_site"
OUTPUT_SENTINEL = ".api-management-studies-generated-output"
OUTPUT_SENTINEL_VALUE = "Generated by scripts/build_site.py; safe to replace.\n"
CONTENT_ROOTS = (
    "docs",
    "architecture",
    "decision-matrix",
    "research",
    "poc",
    "mule-migration",
    "workshops",
    "adr",
    "templates",
    "reports",
)
TEXT_EXTENSIONS = {
    ".md",
    ".mmd",
    ".csv",
    ".yaml",
    ".yml",
    ".json",
    ".txt",
    ".sh",
    ".py",
    ".js",
    ".html",
    ".css",
    ".xml",
    ".toml",
    ".ini",
    ".conf",
    ".dockerfile",
}
MEDIA_EXTENSIONS = {
    ".pdf",
    ".ppt",
    ".pptx",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".svg",
    ".mp4",
    ".webm",
}
TYPE_NAMES = {
    ".md": "markdown",
    ".mmd": "mermaid",
    ".csv": "csv",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".pdf": "pdf",
    ".ppt": "presentation",
    ".pptx": "presentation",
    ".html": "html",
    ".sh": "shell",
    ".py": "python",
    ".js": "javascript",
    ".svg": "image",
    ".png": "image",
    ".jpg": "image",
    ".jpeg": "image",
    ".gif": "image",
    ".webp": "image",
    ".mp4": "video",
    ".webm": "video",
}
SECTION_LABELS = {
    "docs": "Studies",
    "architecture": "Architecture",
    "decision-matrix": "Compare",
    "research": "Research",
    "poc": "PoC & Examples",
    "mule-migration": "Migration",
    "workshops": "Workshops",
    "adr": "Decisions",
    "templates": "Templates",
    "reports": "Reports",
}
TAG_RULES = {
    "kong": ("kong",),
    "azure apim": ("azure apim", "azure api management"),
    "apigee": ("apigee",),
    "mulesoft": ("mulesoft", "mule ", "mule/"),
    "kubernetes": ("kubernetes", "aks", "gateway api"),
    "security": ("security", "oauth", "oidc", "jwt", "mtls", "identity"),
    "architecture": ("architecture", "topology", "control plane", "data plane"),
    "migration": ("migration", "modernization", "decommission", "strangler"),
    "apiops": ("apiops", "pipeline", "declarative configuration"),
    "observability": ("observability", "telemetry", "prometheus", "logging", "metrics"),
    "resilience": ("resilience", "failover", "disaster recovery", "ha/dr"),
    "governance": ("governance", "operating model", "guardrail"),
}

DIAGRAM_COMPANIONS = {
    "architecture/diagrams/apiops-flow.mmd": "architecture/apiops-architecture.md",
    "architecture/diagrams/current-state.mmd": "architecture/current-state.md",
    "architecture/diagrams/dr-failover.mmd": "architecture/ha-dr-architecture.md",
    "architecture/diagrams/east-west.mmd": "architecture/network-architecture.md",
    "architecture/diagrams/hybrid-data-plane.mmd": "architecture/kong-hybrid-architecture.md",
    "architecture/diagrams/kong-control-data-plane.mmd": "architecture/kong-hybrid-architecture.md",
    "architecture/diagrams/mule-decomposition.mmd": "architecture/pcf-aks-transition.md",
    "architecture/diagrams/north-south.mmd": "architecture/network-architecture.md",
    "architecture/diagrams/observability-flow.mmd": "architecture/observability-architecture.md",
    "architecture/diagrams/security-flow.mmd": "architecture/security-architecture.md",
    "architecture/diagrams/target-state.mmd": "architecture/target-state.md",
    "architecture/diagrams/transition-state.mmd": "architecture/transition-state.md",
}

MANIFEST_SCHEMA_VERSION = 1
MANIFEST_GENERATOR = "scripts/build_site.py"
REQUIRED_SITE_ASSET_PATHS = {
    "index.html",
    "404.html",
    "assets/app.js",
    "assets/charts.js",
    "assets/styles.css",
    "assets/audiences.js",
}


def run_git(*args: str) -> str:
    """Return one Git value or fail with a provenance-specific message."""
    try:
        result = subprocess.run(
            ("git", *args),
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", "") or str(exc)
        raise SystemExit(f"Unable to resolve site provenance with git {' '.join(args)}: {detail.strip()}") from exc
    return result.stdout.strip()


def safe_path_location(name: str) -> str:
    """Return a log-safe location without reflecting hostile path text."""
    return f"path-sha256:{hashlib.sha256(name.encode('utf-8', errors='surrogatepass')).hexdigest()[:16]}"


def reject_hidden_index_flags() -> None:
    """Reject Git flags that can hide worktree bytes from clean-state checks."""
    result = subprocess.run(
        ("git", "ls-files", "-v", "-z"),
        cwd=ROOT, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    if result.returncode:
        raise SystemExit("Unable to inspect Git index visibility flags")
    for entry in (value for value in result.stdout.split(b"\0") if value):
        marker = entry[:1]
        if marker == b"S" or marker.islower():
            raise SystemExit("Refusing a build while Git index visibility flags hide worktree state")


def repository_candidate_paths() -> list[Path]:
    """Return tracked plus non-ignored untracked paths without newline ambiguity."""
    reject_hidden_index_flags()
    result = subprocess.run(
        ("git", "ls-files", "-c", "-o", "--exclude-standard", "-z"),
        cwd=ROOT, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    if result.returncode:
        raise SystemExit("Unable to enumerate public build inputs with git ls-files")
    try:
        names = [value.decode("utf-8") for value in result.stdout.split(b"\0") if value]
    except UnicodeDecodeError as exc:
        raise SystemExit("Refusing a non-UTF-8 public build path") from exc
    candidates: list[Path] = []
    for name in names:
        if not name or name != name.strip() or any(unicodedata.category(character).startswith("C") for character in name):
            raise SystemExit("Refusing a public build path containing control or surrounding whitespace")
        path = ROOT / name
        if path.is_symlink():
            raise SystemExit(f"Refusing symlinked public build input at {safe_path_location(name)}")
        candidate = ROOT
        for part in Path(name).parts:
            candidate /= part
            if candidate.is_symlink():
                raise SystemExit(f"Refusing public build input below a symlink at {safe_path_location(name)}")
        if path.is_file():
            candidates.append(path)
    return sorted(set(candidates))


def publishable_content_sources(candidates: list[Path] | None = None) -> list[Path]:
    sources: list[Path] = []
    for source in candidates or repository_candidate_paths():
        relative = source.relative_to(ROOT)
        if not relative.parts or relative.parts[0] not in CONTENT_ROOTS:
            continue
        if any(part.startswith(".") for part in relative.parts):
            continue
        if source.suffix.lower() in TEXT_EXTENSIONS | MEDIA_EXTENSIONS or source.name == "Dockerfile":
            sources.append(source)
    return sources


def site_asset_sources(candidates: list[Path] | None = None) -> list[Path]:
    return [
        source for source in (candidates or repository_candidate_paths())
        if source.relative_to(ROOT).parts[:1] == ("site",)
    ]


def source_revision() -> str:
    """Resolve the built commit in an explicit, CI-safe priority order."""
    candidate = os.environ.get("SOURCE_REVISION") or os.environ.get("GITHUB_SHA") or "HEAD"
    revision = run_git("rev-parse", "--verify", f"{candidate}^{{commit}}")
    if not re.fullmatch(r"[0-9a-f]{40,64}", revision):
        raise SystemExit(f"Resolved source revision is not a full Git object ID: {revision!r}")
    return revision


def source_is_dirty(revision: str) -> bool:
    """Mark raw-byte changes and revision/checkout mismatches as non-reproducible."""
    head = run_git("rev-parse", "--verify", "HEAD^{commit}")
    worktree_changes = run_git("status", "--porcelain=v1", "--untracked-files=all")
    return bool(worktree_changes) or revision != head or not raw_tracked_bytes_match(revision)


def raw_tracked_bytes_match(revision: str) -> bool:
    """Compare worktree bytes with Git blobs without clean/smudge filters."""
    listed = subprocess.run(
        ("git", "ls-files", "-c", "-z"), cwd=ROOT, check=False,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    if listed.returncode:
        raise SystemExit("Unable to enumerate tracked files for raw-byte provenance")
    try:
        names = [value.decode("utf-8") for value in listed.stdout.split(b"\0") if value]
    except UnicodeDecodeError as exc:
        raise SystemExit("Refusing a non-UTF-8 tracked path during raw-byte provenance") from exc
    for name in names:
        path = ROOT / name
        if not path.is_file() or path.is_symlink():
            return False
        expected = subprocess.Popen(
            ("git", "cat-file", "blob", f"{revision}:{name}"), cwd=ROOT,
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        )
        expected_digest = hashlib.sha256()
        assert expected.stdout is not None
        for chunk in iter(lambda: expected.stdout.read(1024 * 1024), b""):
            expected_digest.update(chunk)
        expected.stdout.close()
        if expected.wait() != 0:
            return False
        if sha256_file(path) != expected_digest.hexdigest():
            return False
    return True


def generated_at(revision: str) -> str:
    """Derive build time from reproducible inputs, never the wall clock."""
    epoch_value = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch_value is None:
        epoch_value = run_git("show", "-s", "--format=%ct", revision)
    try:
        epoch = int(epoch_value)
        if epoch < 0:
            raise ValueError
    except ValueError as exc:
        raise SystemExit(f"SOURCE_DATE_EPOCH must be a non-negative integer, got {epoch_value!r}") from exc
    try:
        return datetime.fromtimestamp(epoch, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    except (OverflowError, OSError, ValueError) as exc:
        raise SystemExit(f"SOURCE_DATE_EPOCH is outside the supported timestamp range: {epoch_value!r}") from exc


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def asset_digests(output: Path, sources: list[Path] | None = None) -> dict[str, dict[str, object]]:
    assets: dict[str, dict[str, object]] = {}
    source_assets = {path.relative_to(SITE_SOURCE).as_posix() for path in (sources or site_asset_sources())}
    asset_paths = source_assets | {"404.html"}
    missing = REQUIRED_SITE_ASSET_PATHS - asset_paths
    if missing:
        raise SystemExit(f"Required site asset definitions are missing: {sorted(missing)}")
    for relative in sorted(asset_paths):
        path = output / relative
        if not path.is_file():
            raise SystemExit(f"Required site asset is missing: {path}")
        assets[relative] = {"sha256": sha256_file(path), "size": path.stat().st_size}
    return assets


def slug(value: str) -> str:
    value = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return value or "document"


def safe_text(path: Path) -> str:
    if path.suffix.lower() not in TEXT_EXTENSIONS and path.name != "Dockerfile":
        return ""
    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError) as exc:
        raise SystemExit(f"Refusing unreadable/non-UTF-8 public text source: {path.relative_to(ROOT)}") from exc
    if "\0" in text:
        raise SystemExit(f"Refusing NUL-containing public text source: {path.relative_to(ROOT)}")
    return text


def clean_inline(value: str) -> str:
    value = re.sub(r"!\[[^\]]*\]\([^)]*\)", "", value)
    value = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", value)
    value = re.sub(r"[`*_>#|]", " ", value)
    return re.sub(r"\s+", " ", value).strip(" -")


def document_title(path: Path, text: str) -> str:
    if path.suffix.lower() == ".md":
        heading = re.search(r"^#\s+(.+)$", text, flags=re.MULTILINE)
        if heading:
            return clean_inline(heading.group(1))
    if path.suffix.lower() in {".yaml", ".yml"}:
        info_title = re.search(r"^\s{2}title:\s*[\"']?(.+?)[\"']?\s*$", text, flags=re.MULTILINE)
        if info_title:
            return clean_inline(info_title.group(1))
    return re.sub(r"^\d{2,4}[-_]", "", path.stem).replace("-", " ").replace("_", " ").title()


def document_summary(path: Path, text: str, title: str) -> str:
    if path.suffix.lower() == ".md":
        # Repository control markers (study contracts, diagram provenance, and
        # other HTML comments) are machine-readable metadata, not article copy.
        # Remove complete comments before selecting the first visible paragraph
        # so they cannot leak into cards or search results.
        visible_text = re.sub(r"<!--[\s\S]*?-->", "", text)
        blocks = re.split(r"\n\s*\n", visible_text)
        for block in blocks:
            candidate = clean_inline(block)
            if not candidate or candidate == title or block.lstrip().startswith(("#", "```", "|")):
                continue
            return candidate[:260] + ("…" if len(candidate) > 260 else "")
    if path.suffix.lower() == ".mmd":
        return f"Source diagram for {title}. Open it in the architecture gallery to render the model."
    if path.suffix.lower() == ".csv":
        return f"Structured dataset for {title}, available as a filterable table and download."
    if path.suffix.lower() in {".yaml", ".yml"} and re.search(r"^openapi:\s*", text, flags=re.MULTILINE):
        return f"OpenAPI contract for {title}."
    return f"Repository resource: {title}."


def item_type(path: Path, text: str) -> str:
    suffix = path.suffix.lower()
    if suffix in {".yaml", ".yml"} and re.search(r"^openapi:\s*", text, flags=re.MULTILINE):
        return "openapi"
    if path.name == "Dockerfile":
        return "dockerfile"
    return TYPE_NAMES.get(suffix, "resource")


def item_order(path: Path) -> int:
    match = re.match(r"^(\d+)", path.name)
    return int(match.group(1)) if match else 9999


def make_tags(relative: Path, text: str, section: str) -> list[str]:
    haystack = f"{relative.as_posix()}\n{text[:30000]}".lower()
    tags = [section.lower()]
    for label, needles in TAG_RULES.items():
        if any(needle in haystack for needle in needles):
            tags.append(label)
    return list(dict.fromkeys(tags))[:7]


def collect_items(output: Path, sources: list[Path] | None = None) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    seen_ids: set[str] = set()
    by_root: dict[str, list[Path]] = {root_name: [] for root_name in CONTENT_ROOTS}
    for source in sources or publishable_content_sources():
        by_root[source.relative_to(ROOT).parts[0]].append(source)
    for root_name in CONTENT_ROOTS:
        for source in sorted(by_root[root_name]):
            relative = source.relative_to(ROOT)
            destination = output / "content" / relative
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
            text = safe_text(source)
            title = document_title(source, text)
            section = SECTION_LABELS[root_name]
            kind = item_type(source, text)
            item_id = slug(relative.with_suffix("").as_posix())
            if item_id in seen_ids:
                item_id = f"{item_id}-{len(items)}"
            seen_ids.add(item_id)
            search_text = clean_inline(text[:50000])
            items.append(
                {
                    "id": item_id,
                    "title": title,
                    "path": relative.as_posix(),
                    "contentUrl": f"content/{relative.as_posix()}",
                    "route": f"#/doc/{item_id}",
                    "section": section,
                    "type": kind,
                    "order": item_order(source),
                    "tags": make_tags(relative, text, section),
                    "summary": document_summary(source, text, title),
                    "searchText": search_text,
                    "size": source.stat().st_size,
                    "sha256": sha256_file(source),
                }
            )
    items.sort(key=lambda item: (CONTENT_ROOTS.index(str(item["path"]).split("/", 1)[0]), int(item["order"]), str(item["title"])))
    by_path = {str(item["path"]): item for item in items}
    for diagram_path, companion_path in DIAGRAM_COMPANIONS.items():
        diagram = by_path.get(diagram_path)
        companion = by_path.get(companion_path)
        if diagram and companion:
            diagram["companionId"] = companion["id"]
            diagram["companionPath"] = companion_path
    return items


def count_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def markdown_row(line: str) -> list[str]:
    """Split a pipe-delimited Markdown table row, preserving escaped pipes."""
    stripped = line.strip()
    if not stripped.startswith("|"):
        return []
    stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    return [cell.replace(r"\|", "|").strip() for cell in re.split(r"(?<!\\)\|", stripped)]


def markdown_tables(text: str) -> list[list[dict[str, str]]]:
    """Return all well-formed leading-pipe Markdown tables in a document."""
    lines = text.splitlines()
    tables: list[list[dict[str, str]]] = []
    index = 0
    while index + 1 < len(lines):
        headers = markdown_row(lines[index])
        separator = markdown_row(lines[index + 1])
        if (
            not headers
            or len(headers) != len(separator)
            or not all(re.fullmatch(r":?-{3,}:?", re.sub(r"\s+", "", cell)) for cell in separator)
        ):
            index += 1
            continue
        rows: list[dict[str, str]] = []
        cursor = index + 2
        while cursor < len(lines):
            cells = markdown_row(lines[cursor])
            if not cells:
                break
            if len(cells) < len(headers):
                cells.extend([""] * (len(headers) - len(cells)))
            rows.append(dict(zip(headers, cells[: len(headers)])))
            cursor += 1
        tables.append(rows)
        index = cursor
    return tables


def markdown_table(text: str, required_columns: tuple[str, ...]) -> list[dict[str, str]]:
    """Find a Markdown table by column names instead of by document position."""
    required = {column.casefold() for column in required_columns}
    for rows in markdown_tables(text):
        if not rows:
            continue
        columns = {column.casefold() for column in rows[0]}
        if required.issubset(columns):
            return rows
    return []


def markdown_section(text: str, heading: str, level: int = 2) -> str:
    """Return one exact Markdown heading section for schema-scoped projections."""
    marker = "#" * level
    match = re.search(
        rf"^{re.escape(marker)}\s+{re.escape(heading)}\s*$([\s\S]*?)(?=^{re.escape(marker)}\s+|\Z)",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    return match.group(1) if match else ""


def row_value(row: dict[str, str], column: str) -> str:
    """Read a Markdown table cell case-insensitively."""
    target = column.casefold()
    for key, value in row.items():
        if key.casefold() == target:
            return value.strip()
    return ""


def integer(value: str) -> int:
    try:
        return int(value.strip())
    except (AttributeError, TypeError, ValueError):
        return 0


def label_for(value: str) -> str:
    labels = {
        "api-lifecycle": "API lifecycle",
        "apiops": "APIOps",
        "kubernetes": "Kubernetes",
        "mule-migration": "Mule migration",
        "operations-support": "Operations & support",
        "resilience-performance": "Resilience & performance",
        "traffic-policy": "Traffic & policy",
    }
    return labels.get(value.casefold(), value.replace("-", " ").capitalize())


def count_series(values: list[str]) -> list[dict[str, object]]:
    counts = Counter(value.strip() for value in values if value and value.strip())
    return [
        {"label": label, "value": value}
        for label, value in sorted(counts.items(), key=lambda item: (-item[1], item[0].casefold()))
    ]


def canonical_problem_ids(value: str) -> list[str]:
    """Expand canonical P-ID lists and ranges while preserving first-seen order."""
    # Inline-code markers often wrap each end of a range independently
    # (for example, ``P1``–``P10``); remove them before range matching.
    normalized = value.replace("`", "").replace("—", "-").replace("–", "-")
    problem_ids: list[str] = []
    for match in re.finditer(r"\bP(\d+)(?:\s*-\s*P?(\d+))?\b", normalized, flags=re.IGNORECASE):
        start = int(match.group(1))
        end = int(match.group(2) or start)
        numbers = range(start, end + 1) if end >= start else ()
        for number in numbers:
            problem_id = f"P{number}"
            if problem_id not in problem_ids:
                problem_ids.append(problem_id)
    return problem_ids


def canonical_practice_ids(value: str) -> list[str]:
    """Return canonical BP identifiers while preserving first-seen order."""
    practice_ids: list[str] = []
    for match in re.finditer(r"\bBP-(\d+)\b", value.replace("`", ""), flags=re.IGNORECASE):
        practice_id = f"BP-{int(match.group(1))}"
        if practice_id not in practice_ids:
            practice_ids.append(practice_id)
    return practice_ids


def simple_yaml_numbers(path: Path) -> dict[str, int]:
    """Parse the repository's flat numeric weight map without a YAML dependency."""
    values: dict[str, int] = {}
    for line in safe_text(path).splitlines():
        match = re.match(r"^\s*([a-z0-9-]+)\s*:\s*(\d+)\s*(?:#.*)?$", line, flags=re.IGNORECASE)
        if match:
            values[match.group(1)] = int(match.group(2))
    return values


def criteria_visuals() -> dict[str, object]:
    rows = count_csv_rows(ROOT / "decision-matrix" / "criteria.csv")
    category_weights = simple_yaml_numbers(ROOT / "decision-matrix" / "weights.yaml")
    categories: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        category = row.get("category", "").strip()
        if category:
            categories.setdefault(category, []).append(row)

    category_rows: list[dict[str, object]] = []
    for category, criteria in categories.items():
        requirement_types = [row.get("requirement_type", "").strip().casefold() for row in criteria]
        category_rows.append(
            {
                "id": category,
                "label": label_for(category),
                "total": len(criteria),
                "mandatory": requirement_types.count("mandatory"),
                "weighted": requirement_types.count("weighted"),
                "criterionWeight": sum(integer(row.get("default_weight", "")) for row in criteria),
                "categoryWeight": category_weights.get(category),
            }
        )

    requirement_types = [row.get("requirement_type", "").strip().casefold() for row in rows]
    return {
        "total": len(rows),
        "mandatory": requirement_types.count("mandatory"),
        "weighted": requirement_types.count("weighted"),
        "statuses": count_series([label_for(row.get("status", "")) for row in rows]),
        "categories": category_rows,
        "categoryWeightStatus": "Workshop defaults; not approved",
        "categoryWeightTotal": sum(category_weights.values()),
    }


def scorecard_status(path: Path) -> tuple[str, str]:
    text = safe_text(path)
    match = re.search(r"^Status:\s*\*\*([^*]+)\*\*\.?\s*(.*)$", text, flags=re.MULTILINE | re.IGNORECASE)
    if not match:
        return "Unscored", "Awaiting criterion-level evidence."
    source_status = clean_inline(match.group(1)).casefold()
    if source_status in {"not scored", "unscored"}:
        status = "Unscored"
    elif source_status.startswith("awaiting"):
        # "Awaiting evidence" is still an unscored decision state. Keep the
        # evidence condition in its own field so the comparison view does not
        # imply that one candidate has progressed further than the others.
        status = "Unscored"
    else:
        status = label_for(source_status)
    note = re.sub(r"\s+([.,;:])", r"\1", clean_inline(match.group(2))) or "Awaiting criterion-level evidence."
    return status, note


def variant_scorecard(name: str) -> Path | None:
    normalized = name.casefold()
    if "kong" in normalized:
        return ROOT / "decision-matrix" / "kong-scorecard.md"
    if "apim" in normalized:
        return ROOT / "decision-matrix" / "azure-apim-scorecard.md"
    if "apigee" in normalized:
        return ROOT / "decision-matrix" / "apigee-scorecard.md"
    if "mulesoft" in normalized:
        return ROOT / "decision-matrix" / "mulesoft-baseline.md"
    return None


def variants_visuals() -> list[dict[str, object]]:
    text = safe_text(ROOT / "decision-matrix" / "README.md")
    # The decision model deliberately calls these rows bounded archetypes until
    # Gate 1 resolves exact, scoreable options. Parse that canonical section by
    # meaning so an editorial heading change cannot silently empty the site
    # comparison data again.
    section = re.search(
        r"^##\s+(?:Bounded\s+)?(?:deployment\s+)?(?:archetypes|variants|options)\b[^\n]*$"
        r"([\s\S]*?)(?=^##\s+|\Z)",
        text,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    variant_names = re.findall(r"^\s*\d+\.\s+(.+?)\s*$", section.group(1), flags=re.MULTILINE) if section else []
    variants: list[dict[str, object]] = []
    for raw_name in variant_names:
        name = clean_inline(raw_name)
        scorecard = variant_scorecard(name)
        if scorecard and scorecard.exists():
            status, note = scorecard_status(scorecard)
            source = scorecard.relative_to(ROOT).as_posix()
        else:
            status = "Unscored"
            note = "Awaiting criterion-level evidence; no populated scorecard is present."
            source = "decision-matrix/README.md"
        variants.append(
            {
                "name": name,
                "status": status,
                "note": note,
                "evidenceStatus": "Awaiting evidence",
                "source": source,
            }
        )
    return variants


def sources_visuals() -> dict[str, object]:
    rows = count_csv_rows(ROOT / "research" / "sources.csv")
    findings_text = safe_text(ROOT / "research" / "findings.md")
    source_ids = [row.get("source_id", "").strip() for row in rows if row.get("source_id", "").strip()]
    used_ids = [
        source_id
        for source_id in source_ids
        if re.search(rf"(?<![A-Z0-9-]){re.escape(source_id)}(?![A-Z0-9-])", findings_text, flags=re.IGNORECASE)
    ]
    used_set = set(used_ids)
    unused_ids = [source_id for source_id in source_ids if source_id not in used_set]
    return {
        "total": len(rows),
        "byVendor": count_series([row.get("vendor", "") for row in rows]),
        "byProduct": count_series([row.get("product", "") for row in rows]),
        "usedInFindings": len(used_ids),
        "unusedInFindings": len(unused_ids),
        "usedSourceIds": used_ids,
        "unusedSourceIds": unused_ids,
        "usageDefinition": "Explicit source IDs cited in research/findings.md; aggregate labels such as 'All' are not expanded.",
    }


def findings_visuals() -> dict[str, object]:
    text = safe_text(ROOT / "research" / "findings.md")
    rows = markdown_table(text, ("ID", "State", "Claim", "Sources"))
    return {
        "total": len(rows),
        "byState": count_series([row_value(row, "State") for row in rows]),
    }


def poc_visuals() -> dict[str, object]:
    text = safe_text(ROOT / "poc" / "test-plan.md")
    rows = markdown_table(text, ("ID", "Test", "Baseline status", "Exit evidence"))
    tests = [
        {
            "id": row_value(row, "ID"),
            "label": row_value(row, "Test"),
            "status": row_value(row, "Baseline status"),
            "evidence": row_value(row, "Exit evidence"),
        }
        for row in rows
    ]
    return {
        "total": len(tests),
        "byStatus": count_series([str(test["status"]) for test in tests]),
        "tests": tests,
    }


def governance_visuals() -> dict[str, object]:
    assumptions_text = safe_text(ROOT / "docs" / "02-current-state-assumptions.md")
    assumption_rows = markdown_table(assumptions_text, ("ID", "Assumption", "Status"))

    adr_statuses: list[str] = []
    for path in sorted((ROOT / "adr").glob("*.md")):
        if path.name.casefold() == "readme.md":
            continue
        match = re.search(r"^-\s*Status:\s*(.+?)\s*$", safe_text(path), flags=re.MULTILINE | re.IGNORECASE)
        if match:
            adr_statuses.append(label_for(clean_inline(match.group(1))))

    risks_text = safe_text(ROOT / "docs" / "37-risks.md")
    risk_rows = markdown_table(risks_text, ("ID", "Risk event and consequence", "Owner role"))
    if not risk_rows:
        risk_rows = markdown_table(risks_text, ("ID", "Risk", "Owner"))
    questions_text = safe_text(ROOT / "docs" / "38-open-questions.md")
    question_rows = re.findall(r"^\|\s*Q-\d+\s*\|", questions_text, flags=re.MULTILINE)
    open_questions = len(question_rows) or len(re.findall(r"^\s*\d+\.\s+\S", questions_text, flags=re.MULTILINE))
    return {
        "assumptions": count_series([label_for(row_value(row, "Status")) for row in assumption_rows]),
        "adrs": count_series(adr_statuses),
        "risksByOwner": count_series([row_value(row, "Owner role") or row_value(row, "Owner") for row in risk_rows]),
        "openQuestions": open_questions,
        "assumptionTotal": len(assumption_rows),
        "adrTotal": len(adr_statuses),
        "riskTotal": len(risk_rows),
    }


def library_visuals(items: list[dict[str, object]]) -> dict[str, object]:
    return {
        "bySection": count_series([str(item.get("section", "")) for item in items]),
        "byType": count_series([str(item.get("type", "")) for item in items]),
    }


def roadmap_visuals() -> dict[str, object]:
    text = safe_text(ROOT / "docs" / "36-implementation-roadmap.md")
    rows = markdown_table(text, ("Phase", "Scenario planning range", "Exit evidence—not activity"))
    duration_key = "Scenario planning range"
    exit_key = "Exit evidence—not activity"
    if not rows:
        rows = markdown_table(text, ("Phase", "Indicative duration", "Exit criteria"))
        duration_key = "Indicative duration"
        exit_key = "Exit criteria"
    return {
        "phases": [
            {
                "label": row_value(row, "Phase"),
                "duration": clean_inline(row_value(row, duration_key)),
                "exitCriteria": row_value(row, exit_key),
            }
            for row in rows
        ]
    }


def repository_roadmap_visuals() -> dict[str, object]:
    text = safe_text(ROOT / "docs" / "39-repository-roadmap.md")
    rows = markdown_table(text, ("Phase", "Status", "Primary outcome", "Exit gate"))
    return {
        "phases": [
            {
                "label": row_value(row, "Phase"),
                "duration": clean_inline(row_value(row, "Status")),
                "exitCriteria": (
                    f"{row_value(row, 'Primary outcome')} — {row_value(row, 'Exit gate')}"
                ).strip(" —"),
            }
            for row in rows
        ]
    }


def industry_problem_visuals() -> dict[str, object]:
    """Project the canonical cross-vendor problem taxonomy into chart-ready rows."""
    text = safe_text(ROOT / "docs" / "43-api-management-industry-problems.md")
    rows = markdown_table(
        text,
        (
            "Rank",
            "Enduring problem",
            "Mechanism vendors productize",
            "RE-1 exposure",
            "Decision implication",
        ),
    )
    problems = [
        {
            "id": f"P{clean_inline(row_value(row, 'Rank'))}",
            "label": clean_inline(row_value(row, "Enduring problem")),
            "mechanism": clean_inline(row_value(row, "Mechanism vendors productize")),
            "exposure": clean_inline(row_value(row, "RE-1 exposure")),
            "proof": clean_inline(row_value(row, "Decision implication")),
        }
        for row in rows
    ]
    return {"total": len(problems), "problems": problems}


def industry_practice_visuals() -> dict[str, object]:
    """Project doc45's practices, scenarios, and adoption gates without copied site data."""
    text = safe_text(ROOT / "docs" / "45-api-management-industry-practices.md")
    practice_rows = markdown_table(
        markdown_section(text, "Best-practice framework mapped to P1–P10"),
        (
            "Canonical problem",
            "Required practice",
            "Minimum implementation mechanism",
            "Acceptance evidence",
            "Reject or hold when",
        ),
    )
    scenario_rows = markdown_table(
        markdown_section(text, "Realistic enterprise scenarios"),
        (
            "Scenario",
            "Failure mechanism",
            "Best-practice control",
            "Measurable acceptance",
            "Owner",
        ),
    )
    maturity_rows = markdown_table(
        markdown_section(text, "Capability maturity and adoption sequence"),
        ("Stage", "Operating outcome", "Required evidence", "Exit gate"),
    )

    practices: list[dict[str, object]] = []
    for row in practice_rows:
        problem_label = clean_inline(row_value(row, "Canonical problem"))
        practice_label = clean_inline(row_value(row, "Required practice"))
        problem_ids = canonical_problem_ids(problem_label)
        practice_ids = canonical_practice_ids(practice_label)
        practices.append(
            {
                "problemId": problem_ids[0] if problem_ids else "",
                "problem": problem_label,
                "id": practice_ids[0] if practice_ids else "",
                "label": practice_label,
                "mechanism": clean_inline(row_value(row, "Minimum implementation mechanism")),
                "evidence": clean_inline(row_value(row, "Acceptance evidence")),
                "hold": clean_inline(row_value(row, "Reject or hold when")),
            }
        )

    scenarios: list[dict[str, object]] = []
    for row in scenario_rows:
        scenario_label = clean_inline(row_value(row, "Scenario"))
        match = re.search(r"\bS(\d+)\b", scenario_label, flags=re.IGNORECASE)
        scenario_id = f"S{int(match.group(1))}" if match else ""
        display_label = re.sub(
            r"^\s*S\d+\s*(?:[—–:\-]\s*)?",
            "",
            scenario_label,
            flags=re.IGNORECASE,
        ).strip()
        control = clean_inline(row_value(row, "Best-practice control"))
        scenarios.append(
            {
                "id": scenario_id,
                "label": display_label or scenario_label,
                "failure": clean_inline(row_value(row, "Failure mechanism")),
                "control": control,
                "practiceIds": canonical_practice_ids(control),
                "acceptance": clean_inline(row_value(row, "Measurable acceptance")),
                "owner": clean_inline(row_value(row, "Owner")),
            }
        )

    stages = [
        {
            "id": clean_inline(row_value(row, "Stage")).split(" ", 1)[0],
            "label": clean_inline(row_value(row, "Stage")),
            "outcome": clean_inline(row_value(row, "Operating outcome")),
            "evidence": clean_inline(row_value(row, "Required evidence")),
            "exitGate": clean_inline(row_value(row, "Exit gate")),
        }
        for row in maturity_rows
    ]
    return {
        "practiceTotal": len(practices),
        "practices": practices,
        "scenarioTotal": len(scenarios),
        "scenarios": scenarios,
        "stageTotal": len(stages),
        "stages": stages,
    }


def kong_multicloud_visuals(items: list[dict[str, object]]) -> dict[str, object]:
    """Project Kong option and workstream data without creating a second problem taxonomy."""
    text = safe_text(ROOT / "docs" / "44-kong-multicloud-study-roadmap.md")
    workstream_rows = markdown_table(
        text,
        (
            "Workstream",
            "Canonical problems",
            "Study question",
            "Exact evidence outputs",
            "Owner",
            "Dependencies",
            "Entry gate",
            "Exit gate",
            "Scenario range",
        ),
    )
    option_rows = markdown_table(
        text,
        (
            "Option ID",
            "Bounded archetype",
            "Plane placement and authority",
            "Intended study role",
            "Gate-1 unresolved fields",
            "Evidence transfer prohibited",
        ),
    )
    by_path = {str(item["path"]): str(item["id"]) for item in items}
    problem_source_path = "docs/43-api-management-industry-problems.md"
    workstreams = [
        {
            "id": clean_inline(row_value(row, "Workstream")).split(" ", 1)[0],
            "label": clean_inline(row_value(row, "Workstream")),
            "problemIds": canonical_problem_ids(row_value(row, "Canonical problems")),
            "problemLabel": clean_inline(row_value(row, "Canonical problems")),
            "question": clean_inline(row_value(row, "Study question")),
            "outputs": clean_inline(row_value(row, "Exact evidence outputs")),
            "owner": clean_inline(row_value(row, "Owner")),
            "dependencies": clean_inline(row_value(row, "Dependencies")),
            "entryGate": clean_inline(row_value(row, "Entry gate")),
            "exitGate": clean_inline(row_value(row, "Exit gate")),
            "duration": clean_inline(row_value(row, "Scenario range")),
        }
        for row in workstream_rows
    ]
    options = [
        {
            "id": clean_inline(row_value(row, "Option ID")),
            "label": clean_inline(row_value(row, "Bounded archetype")),
            "placement": clean_inline(row_value(row, "Plane placement and authority")),
            "role": clean_inline(row_value(row, "Intended study role")),
        }
        for row in option_rows
    ]
    return {
        "workstreamTotal": len(workstreams),
        "workstreams": workstreams,
        "optionTotal": len(options),
        "options": options,
        "problemSourcePath": problem_source_path,
        "problemSourceId": by_path.get(problem_source_path, ""),
    }


def methodology_visuals() -> dict[str, object]:
    text = safe_text(ROOT / "docs" / "03-assessment-methodology.md")
    sequence_rows = markdown_table(text, ("Stage", "Purpose", "Required output", "Stop condition"))
    steps = [
        {
            "label": clean_inline(row_value(row, "Stage")),
            "description": (
                f"{row_value(row, 'Purpose')} — Output: {row_value(row, 'Required output')}"
            ).strip(" —"),
        }
        for row in sequence_rows
    ]

    level_rows = markdown_table(text, ("Level", "Evidence", "Permitted score confidence"))
    evidence_levels = [
        {
            "level": clean_inline(row_value(row, "Level")),
            "label": row_value(row, "Evidence"),
            "confidence": row_value(row, "Permitted score confidence"),
        }
        for row in level_rows
    ]
    return {"steps": steps, "evidenceLevels": evidence_levels}


def review_visuals() -> dict[str, object]:
    text = safe_text(ROOT / "reports" / "methodology-review.md")
    rows = markdown_table(text, ("Decision", "Principal recommendation", "Status", "Exit evidence"))
    return {
        "decisions": [
            {
                "name": row_value(row, "Decision"),
                "status": row_value(row, "Status"),
                "recommendation": row_value(row, "Principal recommendation"),
                "exitEvidence": row_value(row, "Exit evidence"),
                "evidenceStatus": (
                    f"{row_value(row, 'Principal recommendation')} — Exit: {row_value(row, 'Exit evidence')}"
                ).strip(" —"),
            }
            for row in rows
        ]
    }


def visual_provenance(items: list[dict[str, object]]) -> dict[str, dict[str, object]]:
    by_path = {str(item["path"]): str(item["id"]) for item in items}
    source_paths = {
        "criteria": ("decision-matrix/criteria.csv", "decision-matrix/weights.yaml"),
        "variants": ("decision-matrix/README.md",),
        "sources": ("research/sources.csv", "research/findings.md"),
        "findings": ("research/findings.md",),
        "poc": ("poc/README.md", "poc/test-plan.md", "poc/real-world-scenarios.md", "poc/portal-tests.md", "poc/observability-tests.md"),
        "governance": ("docs/02-current-state-assumptions.md", "adr/README.md", "docs/37-risks.md", "docs/38-open-questions.md"),
        "roadmap": ("docs/36-implementation-roadmap.md",),
        "repositoryRoadmap": ("docs/39-repository-roadmap.md",),
        "industryProblems": ("docs/43-api-management-industry-problems.md",),
        "industryPractices": ("docs/45-api-management-industry-practices.md",),
        "kongMulticloud": ("docs/44-kong-multicloud-study-roadmap.md",),
        "methodology": ("docs/03-assessment-methodology.md",),
        "review": ("reports/methodology-review.md",),
    }
    provenance: dict[str, dict[str, object]] = {}
    for key, paths in source_paths.items():
        available = [path for path in paths if path in by_path]
        if not available:
            continue
        provenance[key] = {
            "sourcePath": available[0],
            "sourceId": by_path[available[0]],
            "sourcePaths": available,
            "sourceIds": [by_path[path] for path in available],
        }
    provenance["library"] = {
        "sourcePath": "content-manifest.json",
        "sourceHref": "content-manifest.json",
        "sourcePaths": ["content-manifest.json"],
        "sourceIds": [],
    }
    return provenance


def build_visuals(items: list[dict[str, object]]) -> dict[str, object]:
    """Build chart-ready data exclusively from tracked repository content."""
    return {
        "criteria": criteria_visuals(),
        "variants": variants_visuals(),
        "sources": sources_visuals(),
        "findings": findings_visuals(),
        "poc": poc_visuals(),
        "governance": governance_visuals(),
        "library": library_visuals(items),
        "roadmap": roadmap_visuals(),
        "repositoryRoadmap": repository_roadmap_visuals(),
        "industryProblems": industry_problem_visuals(),
        "industryPractices": industry_practice_visuals(),
        "kongMulticloud": kong_multicloud_visuals(items),
        "methodology": methodology_visuals(),
        "review": review_visuals(),
        "provenance": visual_provenance(items),
    }


def validate_site_projection(stats: dict[str, int], visuals: dict[str, object]) -> None:
    """Reject silent content-to-site projection failures before publication."""
    variants = visuals.get("variants")
    methodology = visuals.get("methodology")
    roadmap = visuals.get("roadmap")
    criteria = visuals.get("criteria")
    industry_problems = visuals.get("industryProblems")
    industry_practices = visuals.get("industryPractices")
    kong_multicloud = visuals.get("kongMulticloud")
    checks = {
        "bounded archetypes": isinstance(variants, list) and bool(variants),
        "methodology decision steps": isinstance(methodology, dict) and bool(methodology.get("steps")),
        "delivery roadmap phases": isinstance(roadmap, dict) and bool(roadmap.get("phases")),
        "decision criteria": (
            isinstance(criteria, dict)
            and criteria.get("total") == stats.get("criteria")
            and bool(criteria.get("categories"))
        ),
        "ten enduring industry problems": (
            isinstance(industry_problems, dict)
            and industry_problems.get("total") == 10
            and len(industry_problems.get("problems", [])) == 10
            and [problem.get("id") for problem in industry_problems.get("problems", [])]
            == [f"P{rank}" for rank in range(1, 11)]
        ),
        "ten practices and eight realistic scenarios": (
            isinstance(industry_practices, dict)
            and industry_practices.get("practiceTotal") == 10
            and industry_practices.get("scenarioTotal") == 8
            and industry_practices.get("stageTotal") == 5
            and [practice.get("problemId") for practice in industry_practices.get("practices", [])]
            == [f"P{rank}" for rank in range(1, 11)]
            and [practice.get("id") for practice in industry_practices.get("practices", [])]
            == [f"BP-{rank}" for rank in range(1, 11)]
            and [scenario.get("id") for scenario in industry_practices.get("scenarios", [])]
            == [f"S{rank}" for rank in range(1, 9)]
            and all(scenario.get("practiceIds") for scenario in industry_practices.get("scenarios", []))
            and {
                practice_id
                for scenario in industry_practices.get("scenarios", [])
                for practice_id in scenario.get("practiceIds", [])
            }
            == {f"BP-{rank}" for rank in range(1, 11)}
            and [stage.get("id") for stage in industry_practices.get("stages", [])]
            == [f"IPM-{rank}" for rank in range(0, 5)]
        ),
        "Kong multicloud study workstreams": (
            isinstance(kong_multicloud, dict)
            and bool(kong_multicloud.get("workstreams"))
            and kong_multicloud.get("workstreamTotal") == 13
            and kong_multicloud.get("workstreamTotal") == len(kong_multicloud.get("workstreams", []))
            and [workstream.get("id") for workstream in kong_multicloud.get("workstreams", [])]
            == [f"WS-{number:02d}" for number in range(1, 14)]
            and all(workstream.get("problemIds") for workstream in kong_multicloud.get("workstreams", []))
            and {
                problem_id
                for workstream in kong_multicloud.get("workstreams", [])
                for problem_id in workstream.get("problemIds", [])
            }
            == {f"P{rank}" for rank in range(1, 11)}
            and bool(kong_multicloud.get("problemSourceId"))
        ),
    }
    missing = [label for label, valid in checks.items() if not valid]
    if missing:
        raise ValueError(f"Site projection is incomplete: {', '.join(missing)}")


def build_audiences(
    items: list[dict[str, object]],
    stats: dict[str, int],
    visuals: dict[str, object],
    presentation: list[dict[str, object]],
) -> list[dict[str, object]]:
    """Build six role-specific lenses over the same canonical evidence."""
    by_path = {str(item["path"]): str(item["id"]) for item in items}
    valid_slide_keys = {str(slide.get("key", "")) for slide in presentation}

    criteria = visuals.get("criteria", {})
    criteria = criteria if isinstance(criteria, dict) else {}
    variants = visuals.get("variants", [])
    variants = variants if isinstance(variants, list) else []
    methodology = visuals.get("methodology", {})
    methodology = methodology if isinstance(methodology, dict) else {}
    repository_roadmap = visuals.get("repositoryRoadmap", {})
    repository_roadmap = repository_roadmap if isinstance(repository_roadmap, dict) else {}
    poc = visuals.get("poc", {})
    poc = poc if isinstance(poc, dict) else {}
    governance = visuals.get("governance", {})
    governance = governance if isinstance(governance, dict) else {}

    def length(value: object) -> int:
        return len(value) if isinstance(value, list) else 0

    def series_value(value: object, label: str) -> int:
        if not isinstance(value, list):
            return 0
        for item in value:
            if isinstance(item, dict) and str(item.get("label", "")).casefold() == label.casefold():
                count = item.get("value", 0)
                return count if isinstance(count, int) else 0
        return 0

    def audience(
        *,
        audience_id: str,
        label: str,
        short_label: str,
        group: str,
        verb: str,
        framing: str,
        decision: str,
        action: str,
        questions: tuple[str, ...],
        signals: tuple[tuple[str, int], ...],
        source_paths: tuple[str, ...],
        recommended_route: str,
        visual: str,
        presentation_slides: tuple[str, ...],
    ) -> dict[str, object]:
        missing_sources = [path for path in source_paths if path not in by_path]
        if missing_sources:
            raise ValueError(f"Audience {audience_id} references missing sources: {missing_sources}")
        missing_slides = [key for key in presentation_slides if key not in valid_slide_keys]
        if missing_slides:
            raise ValueError(f"Audience {audience_id} references unknown slides: {missing_slides}")
        return {
            "id": audience_id,
            "label": label,
            "shortLabel": short_label,
            "group": group,
            "verb": verb,
            "framing": framing,
            "decision": decision,
            "action": action,
            "questions": list(questions),
            "signals": [{"label": signal_label, "value": value} for signal_label, value in signals],
            "sourceIds": [by_path[path] for path in source_paths],
            "sourcePaths": list(source_paths),
            "recommendedRoute": recommended_route,
            "visual": visual,
            "presentationSlides": list(presentation_slides),
            "presentationRoute": f"#/present/{audience_id}/0",
        }

    unscored_variants = sum(
        1
        for variant in variants
        if isinstance(variant, dict) and str(variant.get("status", "")).casefold() == "unscored"
    )
    unknown_criteria = series_value(criteria.get("statuses"), "Unknown")
    evidenced_criteria = max(stats.get("criteria", 0) - unknown_criteria, 0)
    not_run_scenarios = series_value(poc.get("byStatus"), "Not run")
    automated_scenarios = series_value(poc.get("byStatus"), "Automated")
    open_assumptions = series_value(governance.get("assumptions"), "Open")
    proposed_adrs = series_value(governance.get("adrs"), "Proposed")

    return [
        audience(
            audience_id="vp-executive",
            label="VP / Executive",
            short_label="Executive",
            group="Leadership",
            verb="Decide",
            framing="Decision, risk, and investment view of the API management study.",
            decision="Is a platform decision supportable now, and which gates must close before investment is approved?",
            action="Approve Gate 0 and the prerequisite-driven evidence-closure phase—not a vendor selection or a 90-day Gate-2 promise.",
            questions=(
                "What decision is requested now, and what is explicitly not being approved?",
                "Which mandatory gates, risks, economics, and exit conditions can still change the direction?",
                "Who owns the decision, evidence threshold, funding, and review date?",
            ),
            signals=(("Criteria with evidence", evidenced_criteria), ("Mandatory gates", stats.get("mandatoryGates", 0)), ("Unscored options", unscored_variants), ("Atomic protocol cases", stats.get("pocProtocolCases", 0))),
            source_paths=("docs/00-executive-summary.md", "docs/43-api-management-industry-problems.md", "docs/45-api-management-industry-practices.md", "docs/44-kong-multicloud-study-roadmap.md", "reports/methodology-review.md", "reports/evidence-state.md", "decision-matrix/findings.md", "docs/42-public-failure-casebook.md", "docs/37-risks.md", "docs/36-implementation-roadmap.md", "docs/39-repository-roadmap.md"),
            recommended_route="#/compare",
            visual="executive",
            presentation_slides=("decision", "industry-problems", "industry-practices", "kong-multicloud-foundations", "kong-multicloud-proof", "landscape", "evidence", "lessons", "delivery", "next"),
        ),
        audience(
            audience_id="directors",
            label="Directors",
            short_label="Directors",
            group="Leadership",
            verb="Mobilize",
            framing="Portfolio, operating-model, capacity, and delivery-accountability view.",
            decision="What must be funded, staffed, governed, sequenced, and evidenced before the next investment gate?",
            action="Turn the roadmap into an accountable plan with public roles or owner IDs, restricted named owners, dates, capacity, dependencies, and exit evidence.",
            questions=("Who owns each workstream, assumption, risk, acceptance decision, and dependency?", "Which environments, people, commercial inputs, and pilots must be funded now?", "What evidence must each phase produce before the program receives more capacity?"),
            signals=(("Open assumptions", open_assumptions), ("Registered risks", stats.get("risks", 0)), ("Proposed ADRs", proposed_adrs), ("Repository phases", length(repository_roadmap.get("phases")))),
            source_paths=("docs/02-current-state-assumptions.md", "docs/43-api-management-industry-problems.md", "docs/45-api-management-industry-practices.md", "docs/44-kong-multicloud-study-roadmap.md", "docs/33-operating-model.md", "docs/36-implementation-roadmap.md", "docs/37-risks.md", "docs/38-open-questions.md", "docs/42-public-failure-casebook.md", "docs/39-repository-roadmap.md", "mule-migration/migration-factory.md"),
            recommended_route="#/doc/docs-33-operating-model",
            visual="directors",
            presentation_slides=("decision", "industry-problems", "industry-practices", "kong-multicloud-foundations", "kong-multicloud-proof", "evidence", "lessons", "proof", "delivery", "next"),
        ),
        audience(
            audience_id="architects",
            label="Architects",
            short_label="Architects",
            group="Architecture",
            verb="Design",
            framing="Logical, deployment, transition, security, network, observability, and resilience view.",
            decision="Does the vendor-neutral logical architecture—and each candidate topology—satisfy the constraints?",
            action="Approve the capability boundary and vendor-neutral logical model before candidate physical topologies are scored.",
            questions=("Where is the gateway/integration boundary, and what must never move into policy?", "Which locality, residency, isolation, identity, network, and recovery constraints shape placement?", "Which current-state, data-flow, transition, and failure assumptions require evidence?"),
            signals=(("Architecture diagrams", stats.get("diagrams", 0)), ("Assessment categories", length(criteria.get("categories"))), ("Mandatory gates", stats.get("mandatoryGates", 0)), ("Evidence levels", length(methodology.get("evidenceLevels")))),
            source_paths=("architecture/current-state.md", "architecture/target-state.md", "docs/43-api-management-industry-problems.md", "docs/45-api-management-industry-practices.md", "docs/44-kong-multicloud-study-roadmap.md", "docs/06-hybrid-cloud-requirements.md", "docs/07-api-gateway-vs-integration-runtime.md", "architecture/network-architecture.md", "architecture/security-architecture.md", "architecture/ha-dr-architecture.md", "docs/42-public-failure-casebook.md"),
            recommended_route="#/architecture",
            visual="architects",
            presentation_slides=("decision", "target-state", "industry-problems", "industry-practices", "kong-multicloud-foundations", "kong-multicloud-proof", "landscape", "system", "lessons", "evidence", "proof"),
        ),
        audience(
            audience_id="developers",
            label="Developers",
            short_label="Developers",
            group="Engineering",
            verb="Build & consume",
            framing="API contract, APIOps, developer experience, policy boundary, and runnable proof view.",
            decision="Can teams design, publish, discover, secure, consume, change, and roll back APIs safely?",
            action="Prove the complete producer and consumer journeys, including approval, promotion, rollback, discovery, and credentials.",
            questions=("How does an API move from contract to production with ownership and breaking-change controls?", "How does a consumer discover, request, test, rotate credentials, and receive support?", "Which behavior belongs in gateway policy versus domain or integration code?"),
            signals=(("API contracts", stats.get("apiContracts", 0)), ("Atomic protocol cases", stats.get("pocProtocolCases", 0)), ("Automated register items", automated_scenarios), ("Register items not run", not_run_scenarios)),
            source_paths=("docs/07-api-gateway-vs-integration-runtime.md", "docs/43-api-management-industry-problems.md", "docs/45-api-management-industry-practices.md", "docs/44-kong-multicloud-study-roadmap.md", "docs/29-apiops-governance.md", "docs/30-developer-portal-api-products.md", "docs/42-public-failure-casebook.md", "poc/portal-tests.md", "poc/real-world-scenarios.md", "docs/35-mule-migration-strategy.md", "mule-migration/migration-patterns.md"),
            recommended_route="#/lab",
            visual="developers",
            presentation_slides=("decision", "industry-problems", "industry-practices", "kong-multicloud-foundations", "kong-multicloud-proof", "system", "lessons", "proof", "delivery"),
        ),
        audience(
            audience_id="devops-sre",
            label="DevOps / SRE",
            short_label="DevOps / SRE",
            group="Operations",
            verb="Operate & recover",
            framing="Runtime, delivery automation, telemetry, failure, performance, support, and recovery view.",
            decision="Can the runtime be operated, observed, recovered, upgraded, and supported under representative conditions?",
            action="Run Kubernetes, disconnection, failure, soak, telemetry, redaction, and recovery exercises against approved SLOs.",
            questions=("What happens during control-plane loss, restart, scaling, dependency failure, and recovery?", "Do telemetry, redaction, runbooks, support boundaries, and on-call demand meet the operating contract?", "Which SLO, RTO, RPO, load, and failure conditions must a representative pilot prove?"),
            signals=(("Atomic protocol cases", stats.get("pocProtocolCases", 0)), ("Register items not run", not_run_scenarios), ("Recorded risks", stats.get("risks", 0)), ("Architecture diagrams", stats.get("diagrams", 0))),
            source_paths=("architecture/observability-architecture.md", "architecture/ha-dr-architecture.md", "architecture/network-architecture.md", "docs/43-api-management-industry-problems.md", "docs/45-api-management-industry-practices.md", "docs/44-kong-multicloud-study-roadmap.md", "docs/42-public-failure-casebook.md", "poc/real-world-scenarios.md", "poc/observability-tests.md", "poc/kubernetes/README.md", "reports/validation-report.md"),
            recommended_route="#/lab",
            visual="devops-sre",
            presentation_slides=("target-state", "industry-problems", "industry-practices", "kong-multicloud-foundations", "kong-multicloud-proof", "system", "lessons", "proof", "delivery", "next"),
        ),
        audience(
            audience_id="platform-teams",
            label="Platform Teams",
            short_label="Platform",
            group="Platform enablement",
            verb="Enable & govern",
            framing="Platform-product, paved-road, tenancy, automation, governance, migration, and adoption view.",
            decision="What service catalogue, paved road, tenancy model, automation, and support contract can teams adopt repeatedly?",
            action="Define the platform product, support tiers, onboarding SLO, tenancy model, decision rights, and unit economics.",
            questions=("Where do platform and domain ownership, standards, shared services, and exceptions divide?", "Which resolved option has a sustainable upgrade, support, staffing, and cost model?", "What is the paved road for onboarding, tenancy, API operations, policy, and migration?"),
            signals=(("Unscored variants", unscored_variants), ("Current-state assumptions", stats.get("assumptions", 0)), ("Proposed ADRs", proposed_adrs), ("Decision criteria", stats.get("criteria", 0))),
            source_paths=("docs/33-operating-model.md", "docs/43-api-management-industry-problems.md", "docs/45-api-management-industry-practices.md", "docs/44-kong-multicloud-study-roadmap.md", "docs/29-apiops-governance.md", "architecture/apiops-architecture.md", "docs/09-product-shortlist.md", "docs/10-kong-deep-dive.md", "docs/19-azure-apim-assessment.md", "docs/21-apigee-assessment.md", "docs/23-mulesoft-current-state-baseline.md"),
            recommended_route="#/doc/docs-33-operating-model",
            visual="platform-teams",
            presentation_slides=("target-state", "industry-problems", "industry-practices", "kong-multicloud-foundations", "kong-multicloud-proof", "landscape", "system", "lessons", "proof", "delivery"),
        ),
    ]


def build_stats(items: list[dict[str, object]]) -> dict[str, int]:
    criteria = count_csv_rows(ROOT / "decision-matrix" / "criteria.csv")
    sources = count_csv_rows(ROOT / "research" / "sources.csv")
    public_failure_cases = sum(
        1 for row in sources if str(row.get("source_id", row.get("id", ""))).startswith("PUB-")
    )
    question_text = safe_text(ROOT / "workshops" / "question-bank.md")
    scenario_text = safe_text(ROOT / "poc" / "test-plan.md")
    protocol_cases = sum(
        len(re.findall(r"^#{2,3}\s+(?:RW|PT|OT)-\d{2}\b", safe_text(path), flags=re.MULTILINE))
        for path in (
            ROOT / "poc" / "real-world-scenarios.md",
            ROOT / "poc" / "portal-tests.md",
            ROOT / "poc" / "observability-tests.md",
        )
    )
    risks_text = safe_text(ROOT / "docs" / "37-risks.md")
    assumptions_text = safe_text(ROOT / "docs" / "02-current-state-assumptions.md")
    questions_text = safe_text(ROOT / "docs" / "38-open-questions.md")
    scenario_rows = markdown_table(scenario_text, ("ID", "Test", "Baseline status", "Exit evidence"))
    risk_rows = markdown_table(
        risks_text,
        ("ID", "Risk event and consequence", "Early indicator / trigger", "Treatment and contingency", "Owner role"),
    )
    if not risk_rows:
        risk_rows = markdown_table(risks_text, ("ID", "Risk", "Early indicator", "Mitigation", "Owner"))
    assumption_rows = markdown_table(
        assumptions_text,
        ("ID", "Unvalidated assumption", "Validation owner", "Status"),
    )
    if not assumption_rows:
        assumption_rows = markdown_table(assumptions_text, ("ID", "Assumption", "Validation owner", "Status"))
    question_rows = re.findall(r"^\|\s*Q-\d+\s*\|", questions_text, flags=re.MULTILINE)
    return {
        "resources": len(items),
        "studies": sum(1 for item in items if str(item["path"]).startswith("docs/") and re.match(r"docs/\d{2}-", str(item["path"]))),
        "diagrams": sum(1 for item in items if item["type"] == "mermaid"),
        "criteria": len(criteria),
        "mandatoryGates": sum(1 for row in criteria if row.get("requirement_type", "").lower() == "mandatory"),
        "sources": len(sources),
        "publicFailureCases": public_failure_cases,
        "workshops": sum(1 for item in items if re.match(r"workshops/\d{2}-", str(item["path"]))),
        "questions": len(re.findall(r"^Q-\d{3}\.", question_text, flags=re.MULTILINE)),
        "apiContracts": sum(1 for item in items if item["type"] == "openapi"),
        "pocScenarios": len(scenario_rows),
        "pocProtocolCases": protocol_cases,
        "risks": len(risk_rows),
        "assumptions": len(assumption_rows),
        "openQuestions": len(question_rows) or len(re.findall(r"^\s*\d+\.\s+", questions_text, flags=re.MULTILINE)),
    }


def make_presentation(items: list[dict[str, object]], stats: dict[str, int], visuals: dict[str, object]) -> list[dict[str, object]]:
    by_path = {str(item["path"]): str(item["id"]) for item in items}
    variant_total = len(visuals.get("variants", []))
    variant_scope = f"all {variant_total} bounded archetypes" if variant_total else "all bounded archetypes"
    roadmap_phase_total = len(visuals.get("roadmap", {}).get("phases", []))
    industry_problem_total = int(visuals.get("industryProblems", {}).get("total", 0))
    industry_scenario_total = int(visuals.get("industryPractices", {}).get("scenarioTotal", 0))
    kong_workstreams = list(visuals.get("kongMulticloud", {}).get("workstreams", []))
    kong_split_index = (len(kong_workstreams) + 1) // 2
    kong_foundation_total = len(kong_workstreams[:kong_split_index])
    kong_proof_total = len(kong_workstreams[kong_split_index:])
    specs = [
        ("orientation", "Orientation", "A living evidence base for API management decisions", "Research, architecture, proof, and reusable delivery material in one navigable system.", "docs/00-executive-summary.md", stats["resources"], "indexed resources", "composition"),
        ("decision", "Decision", "Approve evidence closure—not platform selection", f"Run one evidence-led screen across {variant_scope}; resolve each option before scoring, then fund symmetric proof only for approved finalists. Named sequencing hypotheses confer no priority.", "reports/methodology-review.md", "NOW", "evidence closure", "recommendation"),
        ("industry-problems", "Industry agenda", "Start with the enduring problems—not vendor packaging", "The canonical taxonomy ties each API-management pressure to enterprise exposure and the equivalent decision proof required.", "docs/43-api-management-industry-problems.md", industry_problem_total, "enduring problem families", "problemMatrix"),
        ("industry-practices", "Industry practices", "Prove the operating system in realistic cases", "The canonical study maps eight synthetic practice scenarios to named best-practice controls, measurable acceptance, and accountable owners. Every RE-1 or case-local value remains an assumption until execution produces evidence.", "docs/45-api-management-industry-practices.md", industry_scenario_total, "synthetic practice scenarios", "scenarioMatrix"),
        ("kong-multicloud-foundations", "Kong study roadmap · 1/2", "Calibrate topology, trust, change, and resilience", "WS-01 through WS-07 establish the comparative contract, resolve exact options, map plane and trust boundaries, prove configuration authority, and test runtime resilience without presuming selection.", "docs/44-kong-multicloud-study-roadmap.md", kong_foundation_total, "foundation workstreams", "studyRoadmap"),
        ("kong-multicloud-proof", "Kong study roadmap · 2/2", "Prove operations, adoption, exit, and estate truth", "WS-08 through WS-13 close observability, consumer lifecycle, operating economics, migration, emerging-protocol boundaries, and estate ownership before the multicloud hypothesis can advance.", "docs/44-kong-multicloud-study-roadmap.md", kong_proof_total, "proof workstreams", "studyRoadmap"),
        ("target-state", "Target state", "Workload-local data planes, centrally governed", "A vendor-neutral logical view keeps latency and failure boundaries near workloads while governance stays coherent; candidate physical views must prove their own control, persistence, telemetry, and support boundaries.", "architecture/diagrams/target-state.mmd", stats["diagrams"], "architecture views", "architectureDiagram"),
        ("landscape", "Landscape", "Bounded archetypes, no presumed finalist", "Kong, Azure API Management, Apigee, and the MuleSoft baseline remain symmetric research objects until Gate 1 resolves their deployable options and common evidence supports an E3 down-select.", "docs/09-product-shortlist.md", variant_total, "bounded archetypes", "statusMatrix"),
        ("system", "System", "Make the transition reversible", "The transition view makes coexistence, weighted cutover, integration decomposition, rollback, and retirement evidence visible.", "architecture/diagrams/transition-state.mmd", stats["diagrams"], "renderable diagrams", "architectureDiagram"),
        ("lessons", "Failure evidence", "Real incidents change the test plan", "Public postmortems show how fast configuration, valid state, regional failover, trust transitions, and generated artifacts can fail across identical replicas. Every finalist must prove bounded propagation, fail-small behavior, reconciliation, and independent recovery access.", "docs/42-public-failure-casebook.md", stats["publicFailureCases"], "public failure cases", "architectureDiagram"),
        ("evidence", "Evidence", "Unknown stays unknown", "Mandatory gates are scored before weighted preferences. Claims require authoritative evidence or execution proof.", "decision-matrix/criteria.csv", stats["mandatoryGates"], "mandatory gates", "donut"),
        ("research", "Research", "Trace decision-bearing claims to sources", "The authoritative register and finding states separate score-capable evidence from interpretation, assumptions, risks, recommendations, and contextual citations awaiting promotion.", "research/findings.md", stats["sources"], "registered sources", "sourceBalance"),
        ("proof", "Proof", "Turn architecture claims into hard-gated experiments", f"The PoC keeps {stats['pocScenarios']} status-register items distinct from {stats['pocProtocolCases']} atomic real-world, portal, and observability cases; overlapping or aggregate cases are never summed as execution progress.", "poc/README.md", stats["pocProtocolCases"], "decision-grade experiment cases", "pocStatus"),
        ("delivery", "Delivery", "Move in controlled waves", "The roadmap combines discovery, evidence closure, PoC execution, operating-model design, migration waves, and decision gates.", "docs/36-implementation-roadmap.md", roadmap_phase_total, "roadmap phases", "roadmap"),
        ("next", "Next", "Close the evidence gaps that can change the decision", "Open questions remain first-class work. The portal is designed to expose uncertainty, not decorate it.", "docs/38-open-questions.md", stats["openQuestions"], "open questions", "governance"),
    ]
    slides = [
        {
            "index": index,
            "key": key,
            "eyebrow": eyebrow,
            "title": title,
            "body": body,
            "sourceId": by_path.get(path, ""),
            "metric": metric,
            "metricLabel": metric_label,
            "visual": visual,
        }
        for index, (key, eyebrow, title, body, path, metric, metric_label, visual) in enumerate(specs)
    ]
    workstream_ids = {
        "kong-multicloud-foundations": [str(workstream.get("id", "")) for workstream in kong_workstreams[:kong_split_index]],
        "kong-multicloud-proof": [str(workstream.get("id", "")) for workstream in kong_workstreams[kong_split_index:]],
    }
    for slide in slides:
        if slide["key"] in workstream_ids:
            slide["workstreamIds"] = workstream_ids[slide["key"]]
    return slides


def validated_output_path(output: Path) -> Path:
    """Return a safe output path before any recursive replacement occurs."""
    lexical = output if output.is_absolute() else ROOT / output
    if lexical.is_symlink():
        raise SystemExit(f"Refusing symlinked site output: {lexical}")
    resolved = lexical.resolve()
    default = DEFAULT_OUTPUT.resolve()
    if resolved == default:
        if resolved.exists():
            sentinel = resolved / OUTPUT_SENTINEL
            if not resolved.is_dir() or not sentinel.is_file() or sentinel.read_text(encoding="utf-8") != OUTPUT_SENTINEL_VALUE:
                raise SystemExit(f"Refusing to replace an existing unowned output directory: {resolved}")
        return resolved
    if resolved == Path(resolved.anchor) or ROOT.is_relative_to(resolved):
        raise SystemExit(f"Refusing site output that contains the repository: {resolved}")
    if resolved.is_relative_to(ROOT):
        raise SystemExit(f"Only {DEFAULT_OUTPUT} may be replaced inside the repository: {resolved}")
    if resolved.exists():
        sentinel = resolved / OUTPUT_SENTINEL
        if not resolved.is_dir() or not sentinel.is_file() or sentinel.read_text(encoding="utf-8") != OUTPUT_SENTINEL_VALUE:
            raise SystemExit(f"Refusing to replace an existing unowned output directory: {resolved}")
    return resolved


def build(output: Path) -> None:
    if not SITE_SOURCE.exists():
        raise SystemExit(f"Site source is missing: {SITE_SOURCE}")
    output = validated_output_path(output)
    revision = source_revision()
    dirty = source_is_dirty(revision)
    timestamp = generated_at(revision)
    candidates = repository_candidate_paths()
    content_sources = publishable_content_sources(candidates)
    asset_sources = site_asset_sources(candidates)
    if output.exists():
        shutil.rmtree(output)
    output.mkdir(parents=True)
    for source in asset_sources:
        destination = output / source.relative_to(SITE_SOURCE)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
    (output / OUTPUT_SENTINEL).write_text(OUTPUT_SENTINEL_VALUE, encoding="utf-8")
    shutil.copy2(output / "index.html", output / "404.html")
    items = collect_items(output, content_sources)
    stats = build_stats(items)
    visuals = build_visuals(items)
    validate_site_projection(stats, visuals)
    presentation = make_presentation(items, stats, visuals)
    manifest = {
        "schemaVersion": MANIFEST_SCHEMA_VERSION,
        "sourceRevision": revision,
        "sourceDirty": dirty,
        "generatedAt": timestamp,
        "generator": {
            "path": MANIFEST_GENERATOR,
            "sha256": sha256_file(ROOT / MANIFEST_GENERATOR),
        },
        "site": {"title": "API Management Studies", "description": "A living research, architecture, comparison, and proof-of-concept library."},
        "assets": asset_digests(output, asset_sources),
        "stats": stats,
        "visuals": visuals,
        "audiences": build_audiences(items, stats, visuals, presentation),
        "items": items,
        "presentation": presentation,
    }
    (output / "content-manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (output / ".nojekyll").touch()
    state = "dirty" if dirty else "clean"
    print(f"Built {output} with {len(items)} resources from {revision} ({state})")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output directory")
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    build(output)


if __name__ == "__main__":
    main()
