#!/usr/bin/env python3
"""Validate static-site provenance, routes, and byte-for-byte source mirrors."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import unicodedata
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))
from repository_inventory import git_environment


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_VERSION = 2
GENERATOR_PATH = "scripts/build_site.py"
OUTPUT_SENTINEL = ".api-management-studies-generated-output"
OUTPUT_SENTINEL_VALUE = "Generated by scripts/build_site.py; safe to replace.\n"
CONTENT_ROOTS = (
    "docs", "architecture", "decision-matrix", "research", "poc", "mule-migration",
    "workshops", "adr", "templates", "reports",
)
PUBLISHABLE_EXTENSIONS = {
    ".md", ".mmd", ".csv", ".yaml", ".yml", ".json", ".txt", ".sh", ".py",
    ".js", ".html", ".css", ".xml", ".toml", ".ini", ".conf", ".dockerfile",
    ".pdf", ".ppt", ".pptx", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg",
    ".mp4", ".webm",
}
REQUIRED_ASSET_PATHS = {
    "index.html",
    "404.html",
    "assets/app.js",
    "assets/charts.js",
    "assets/styles.css",
    "assets/audiences.js",
}
ALLOWED_EXTERNAL_SCRIPTS = {
    "https://cdn.jsdelivr.net/npm/dompurify@3.2.6/dist/purify.min.js": "sha384-JEyTNhjM6R1ElGoJns4U2Ln4ofPcqzSsynQkmEc/KGy6336qAZl70tDLufbkla+3",
    "https://cdn.jsdelivr.net/npm/marked@15.0.12/marked.min.js": "sha384-948ahk4ZmxYVYOc+rxN1H2gM1EJ2Duhp7uHtZ4WSLkV4Vtx5MUqnV+l7u9B+jFv+",
    "https://cdn.jsdelivr.net/npm/mermaid@11.12.0/dist/mermaid.min.js": "sha384-o+g/BxPwhi0C3RK7oQBxQuNimeafQ3GE/ST4iT2BxVI4Wzt60SH4pq9iXVYujjaS",
}
REQUIRED_LOCAL_SCRIPTS = {"assets/app.js", "assets/charts.js", "assets/audiences.js"}
STATIC_ROUTES = {
    "#/overview",
    "#/library",
    "#/compare",
    "#/architecture",
    "#/lab",
    "#/visuals",
    "#/audiences",
}
KONG_PLATFORM_FIT_SLIDE_KEYS = (
    "kong-platform-fit-boundary",
    "kong-platform-fit-runtime",
    "kong-platform-fit-change",
    "kong-platform-fit-fallback",
)
KONG_PLATFORM_FIT_IDS = tuple(f"KPS-FIT-{index:02d}" for index in range(1, 8))
KONG_PLATFORM_FIT_SLIDE_ROWS = {
    "kong-platform-fit-boundary": ("KPS-FIT-01", "KPS-FIT-02"),
    "kong-platform-fit-runtime": ("KPS-FIT-03", "KPS-FIT-04"),
    "kong-platform-fit-change": ("KPS-FIT-05", "KPS-FIT-06"),
    "kong-platform-fit-fallback": ("KPS-FIT-07",),
}
REMOVED_KONG_PLATFORM_FIT_SLIDE_KEYS = frozenset({"kong-platform-fit-1", "kong-platform-fit-2"})
KONG_PLATFORM_JOURNEY_DECK_ID = "kong-platform-journey"
KONG_PLATFORM_JOURNEY_SLIDE_KEYS = (
    "kong-journey-decision",
    "kong-journey-options",
    "kong-journey-selected-option",
    "kong-platform-architecture",
    "kong-technical-state-trust",
    "kong-technical-degraded-mode",
    "kong-technical-operating-model",
    "kong-platform-roadmap",
    "kong-journey-migration-boundary",
    "kong-journey-migration-coexistence",
    "kong-journey-migration-waves",
    "kong-journey-proof",
    "kong-platform-outcomes-1",
    "kong-platform-outcomes-2",
    "kong-technical-assurance",
)
KONG_PLATFORM_JOURNEY_ROLE_IDS = (
    "vp-executive", "directors", "architects", "developers", "devops-sre", "platform-teams",
)
KONG_PLATFORM_JOURNEY_SOURCE_PATHS = (
    "docs/47-kong-enterprise-platform-strategy.md",
    "docs/44-kong-multicloud-study-roadmap.md",
    "docs/35-mule-migration-strategy.md",
    "poc/README.md",
)
KONG_PLATFORM_JOURNEY_SOURCE_IDS = (
    "docs-47-kong-enterprise-platform-strategy",
    "docs-44-kong-multicloud-study-roadmap",
    "docs-35-mule-migration-strategy",
    "poc-readme",
)
KONG_PLATFORM_JOURNEY_PHASES = (
    ("01", "Options", "Fix custody, runtime, and evidence ownership"),
    ("02", "Architecture", "Separate management state from request execution"),
    ("03", "Adoption", "Turn installation into a paved, supportable platform"),
    ("04", "Migration", "Move representative slices with route-back; retire only after dependency zero"),
    ("05", "Production", "Scale only accepted patterns; narrow, switch, or exit otherwise"),
)
KONG_MULTICLOUD_OPTION_IDS = (
    "KMC-1", "KMC-2", "KMC-3", "KMC-4A", "KMC-4B", "KMC-5", "KMC-6", "KMC-7",
)
MULE_MIGRATION_SOURCE_PATH = "docs/35-mule-migration-strategy.md"
MULE_MIGRATION_SOURCE_ID = "docs-35-mule-migration-strategy"
MULE_RESPONSIBILITY_IDS = ("G", "F", "T", "O", "M", "B", "C", "R")
MULE_WAVE_IDS = tuple(f"M{index}" for index in range(6))
MULE_FIGURE_HEADINGS = {
    "MULE-2": "Mechanism analysis: decompose before selecting a target",
    "MULE-3": "Target coexistence architecture",
    "MULE-6": "Migration waves",
}
POC_STATUS_COUNTS = {"Automated": 5, "Not run": 11}
POC_STATUS_BY_ID = {
    **{f"POC-{index:03d}": "Automated" for index in range(1, 6)},
    "POC-006": "Not run",
    **{f"POC-{index}": "Not run" for index in range(101, 111)},
}
POC_TEST_IDS = tuple(POC_STATUS_BY_ID)
SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")
REVISION_PATTERN = re.compile(r"[0-9a-f]{40,64}")


class ValidationError(RuntimeError):
    """A deterministic site artifact failed its publication contract."""


class ScriptSourceParser(HTMLParser):
    """Collect browser-parsed script tags regardless of attribute quoting."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.scripts: list[list[tuple[str, str | None]]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() == "script":
            self.scripts.append(attrs)

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValidationError(message)


def run_git(*args: str) -> str:
    try:
        result = subprocess.run(
            ("git", *args),
            cwd=ROOT,
            env=git_environment(),
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError) as exc:
        detail = getattr(exc, "stderr", "") or str(exc)
        raise ValidationError(f"git {' '.join(args)} failed: {detail.strip()}") from exc
    return result.stdout.strip()


def safe_path_location(name: str) -> str:
    return f"path-sha256:{hashlib.sha256(name.encode('utf-8', errors='surrogatepass')).hexdigest()[:16]}"


def reject_hidden_index_flags() -> None:
    result = subprocess.run(
        ("git", "ls-files", "-v", "-z"),
        cwd=ROOT, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        env=git_environment(),
    )
    require(result.returncode == 0, "unable to inspect Git index visibility flags")
    for entry in (value for value in result.stdout.split(b"\0") if value):
        marker = entry[:1]
        require(marker != b"S" and not marker.islower(), "Git index visibility flags hide worktree state")


def repository_candidate_paths() -> list[Path]:
    reject_hidden_index_flags()
    result = subprocess.run(
        ("git", "ls-files", "-c", "-o", "--exclude-standard", "-z"),
        cwd=ROOT, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        env=git_environment(),
    )
    require(result.returncode == 0, "unable to enumerate publishable source candidates")
    try:
        names = [value.decode("utf-8") for value in result.stdout.split(b"\0") if value]
    except UnicodeDecodeError as exc:
        raise ValidationError("publishable source path is not UTF-8") from exc
    modes = subprocess.run(
        ("git", "ls-files", "-s", "-z"),
        cwd=ROOT,
        env=git_environment(),
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    require(
        modes.returncode == 0 and all(
            entry.split(b" ", 1)[0] in {b"100644", b"100755"}
            for entry in modes.stdout.split(b"\0") if entry
        ),
        "publishable source contains a non-regular tracked Git mode",
    )
    paths: list[Path] = []
    for name in names:
        require(bool(name) and "%" not in name and name == name.strip() and not any(unicodedata.category(character).startswith("C") for character in name), "publishable source path contains percent, control, or surrounding whitespace")
        path = ROOT / name
        require(not path.is_symlink(), f"publishable source is a symlink at {safe_path_location(name)}")
        candidate = ROOT
        for part in Path(name).parts:
            candidate /= part
            require(not candidate.is_symlink(), f"publishable source is below a symlink at {safe_path_location(name)}")
        if path.is_file():
            paths.append(path)
    return sorted(set(paths))


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def raw_tracked_bytes_match(revision: str) -> bool:
    """Compare worktree bytes to revision blobs without Git content filters."""
    listed = subprocess.run(
        ("git", "ls-files", "-c", "-z"), cwd=ROOT, env=git_environment(), check=False,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    require(listed.returncode == 0, "unable to enumerate tracked raw-byte provenance")
    try:
        names = [value.decode("utf-8") for value in listed.stdout.split(b"\0") if value]
    except UnicodeDecodeError as exc:
        raise ValidationError("tracked provenance path is not UTF-8") from exc
    for name in names:
        path = ROOT / name
        if not path.is_file() or path.is_symlink():
            return False
        expected = subprocess.Popen(
            ("git", "cat-file", "blob", f"{revision}:{name}"), cwd=ROOT, env=git_environment(),
            stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
        )
        expected_digest = hashlib.sha256()
        assert expected.stdout is not None
        for chunk in iter(lambda: expected.stdout.read(1024 * 1024), b""):
            expected_digest.update(chunk)
        expected.stdout.close()
        if expected.wait() != 0:
            return False
        if sha256_file(path) != expected_digest.hexdigest():
            return False
    return True


def safe_relative(value: Any, label: str) -> PurePosixPath:
    require(isinstance(value, str) and bool(value), f"{label} must be a non-empty string")
    split = urlsplit(value)
    require(not split.scheme and not split.netloc and not split.query and not split.fragment, f"{label} must be a relative path without query or fragment")
    require(split.path == value, f"{label} must contain only a canonical path")
    require("%" not in value, f"{label} must not contain percent-encoded or literal percent syntax")
    relative = PurePosixPath(value)
    require(not relative.is_absolute(), f"{label} must be relative: {value!r}")
    require(".." not in relative.parts and "." not in relative.parts, f"{label} is not normalized: {value!r}")
    require("\\" not in value and "//" not in value, f"{label} must use a normalized POSIX path: {value!r}")
    require(relative.as_posix() == value, f"{label} must be canonical POSIX syntax: {value!r}")
    return relative


def under(base: Path, relative: PurePosixPath, label: str) -> Path:
    candidate = (base / Path(*relative.parts)).resolve()
    require(candidate.is_relative_to(base.resolve()), f"{label} escapes {base}: {relative}")
    return candidate


def unique(values: list[str], label: str) -> None:
    require(len(values) == len(set(values)), f"{label} contains duplicate values")


def validate_poc_projection(manifest: dict[str, Any]) -> None:
    """Bind the PoC visual to the canonical aggregate status register."""
    visuals = manifest.get("visuals")
    require(isinstance(visuals, dict), "visuals must be an object")
    poc = visuals.get("poc")
    require(isinstance(poc, dict), "visuals.poc must be an object")

    total = poc.get("total")
    require(type(total) is int and total > 0, "visuals.poc.total must be a positive integer")

    by_status = poc.get("byStatus")
    require(isinstance(by_status, list) and bool(by_status), "visuals.poc.byStatus must be a non-empty list")
    require(all(isinstance(item, dict) for item in by_status), "visuals.poc.byStatus entries must be objects")
    status_labels: list[str] = []
    status_counts: list[int] = []
    for item in by_status:
        label = item.get("label")
        value = item.get("value")
        require(isinstance(label, str) and bool(label), "visuals.poc.byStatus labels must be non-empty strings")
        require(type(value) is int and value >= 0, f"visuals.poc.byStatus value for {label} must be a non-negative integer")
        status_labels.append(label)
        status_counts.append(value)
    unique(status_labels, "visuals.poc.byStatus labels")
    require(sum(status_counts) == total, "visuals.poc.byStatus counts must sum to visuals.poc.total")
    declared_statuses = dict(zip(status_labels, status_counts))
    require(
        declared_statuses == POC_STATUS_COUNTS,
        "visuals.poc.byStatus must be exactly Automated=5 and Not run=11",
    )

    tests = poc.get("tests")
    require(isinstance(tests, list), "visuals.poc.tests must be a list")
    require(len(tests) == total, "visuals.poc.tests length must equal visuals.poc.total")
    require(all(isinstance(test, dict) for test in tests), "visuals.poc.tests entries must be objects")
    test_ids: list[str] = []
    test_statuses: list[str] = []
    for test in tests:
        test_id = test.get("id")
        status = test.get("status")
        require(isinstance(test_id, str) and bool(test_id), "visuals.poc.tests IDs must be non-empty strings")
        require(isinstance(status, str) and status in declared_statuses, f"visuals.poc.tests status for {test_id} is undeclared")
        test_ids.append(test_id)
        test_statuses.append(status)
    unique(test_ids, "visuals.poc.tests IDs")
    require(
        len(test_ids) == len(POC_TEST_IDS) and set(test_ids) == set(POC_TEST_IDS),
        "visuals.poc.tests IDs must be exactly POC-001 through POC-006 and POC-101 through POC-110",
    )
    observed_statuses = {
        label: sum(status == label for status in test_statuses)
        for label in declared_statuses
    }
    require(
        observed_statuses == declared_statuses,
        "visuals.poc.tests status counts must match visuals.poc.byStatus",
    )
    require(
        dict(zip(test_ids, test_statuses)) == POC_STATUS_BY_ID,
        "visuals.poc.tests must preserve the canonical ID-to-status assignments",
    )


def validate_kong_platform_fit_slides(
    manifest: dict[str, Any],
    presentation: list[dict[str, Any]],
) -> None:
    """Bind every Kong fit slide to the canonical seven-row projection."""
    visuals = manifest.get("visuals")
    require(isinstance(visuals, dict), "visuals must be an object")
    strategy = visuals.get("kongPlatformStrategy")
    require(isinstance(strategy, dict), "visuals.kongPlatformStrategy must be an object")
    fit = strategy.get("fit")
    require(isinstance(fit, dict), "visuals.kongPlatformStrategy.fit must be an object")
    rows = fit.get("rows")
    require(isinstance(rows, list) and bool(rows), "canonical Kong platform fit rows must be a non-empty list")
    require(all(isinstance(row, dict) for row in rows), "canonical Kong platform fit rows must be objects")
    canonical_ids = [row.get("projectionId") for row in rows]
    require(
        all(isinstance(row_id, str) and row_id for row_id in canonical_ids),
        "canonical Kong platform fit IDs must be non-empty strings",
    )
    unique(canonical_ids, "canonical Kong platform fit IDs")
    require(
        len(canonical_ids) == len(KONG_PLATFORM_FIT_IDS)
        and set(canonical_ids) == set(KONG_PLATFORM_FIT_IDS),
        "canonical Kong platform fit IDs must be exactly KPS-FIT-01 through KPS-FIT-07",
    )

    slides_by_key = {slide["key"]: slide for slide in presentation}
    require(
        not REMOVED_KONG_PLATFORM_FIT_SLIDE_KEYS.intersection(slides_by_key),
        "presentation retains a removed Kong platform fit slide",
    )
    fit_slide_keys = {
        slide["key"]
        for slide in presentation
        if slide.get("visual") == "kongPlatformFit"
    }
    require(
        fit_slide_keys == set(KONG_PLATFORM_FIT_SLIDE_KEYS),
        "presentation Kong platform fit slides must be exactly the four semantic fit slide keys",
    )
    require(
        all(key in slides_by_key for key in KONG_PLATFORM_FIT_SLIDE_KEYS),
        "presentation must contain the four semantic Kong platform fit slides",
    )
    for key in KONG_PLATFORM_FIT_SLIDE_KEYS:
        require(
            slides_by_key[key].get("visual") == "kongPlatformFit",
            f"slide {key} must use the kongPlatformFit visual",
        )
        require(
            tuple(slides_by_key[key].get("rowIds", ())) == KONG_PLATFORM_FIT_SLIDE_ROWS[key],
            f"slide {key} rowIds do not match its bounded Kong fit contract",
        )

    canonical_id_set = set(canonical_ids)
    for slide in presentation:
        if slide.get("visual") != "kongPlatformFit":
            continue
        key = slide["key"]
        row_ids = slide.get("rowIds")
        require(isinstance(row_ids, list) and bool(row_ids), f"slide {key} rowIds must be a non-empty list")
        require(
            all(isinstance(row_id, str) and row_id for row_id in row_ids),
            f"slide {key} rowIds must be non-empty strings",
        )
        unique(row_ids, f"slide {key} rowIds")
        require(
            set(row_ids).issubset(canonical_id_set),
            f"slide {key} rowIds reference an unknown canonical Kong platform fit ID",
        )

    semantic_row_ids = [
        row_id
        for key in KONG_PLATFORM_FIT_SLIDE_KEYS
        for row_id in slides_by_key[key]["rowIds"]
    ]
    require(
        len(semantic_row_ids) == len(KONG_PLATFORM_FIT_IDS)
        and set(semantic_row_ids) == set(KONG_PLATFORM_FIT_IDS),
        "semantic Kong platform fit slides must cover KPS-FIT-01 through KPS-FIT-07 exactly once",
    )


def validate_kong_platform_journey(
    manifest: dict[str, Any],
    presentation: list[dict[str, Any]],
) -> None:
    """Bind the Kong platform journey to its exact narrative and evidence payload."""
    decks = manifest.get("presentationDecks")
    require(isinstance(decks, list), "presentationDecks must be a list")
    matches = [
        deck for deck in decks
        if isinstance(deck, dict) and deck.get("id") == KONG_PLATFORM_JOURNEY_DECK_ID
    ]
    require(
        len(matches) == 1,
        "presentationDecks must contain exactly one kong-platform-journey deck",
    )
    deck = matches[0]
    require(deck.get("theme") == "kong-journey", "Kong platform journey theme must be kong-journey")
    require(
        tuple(deck.get("presentationSlides", ())) == KONG_PLATFORM_JOURNEY_SLIDE_KEYS,
        "Kong platform journey slides must match the exact 15-slide journey order",
    )
    require(deck.get("slideTotal") == 15, "Kong platform journey slideTotal must be 15")
    require(
        tuple(deck.get("audienceRoleIds", ())) == KONG_PLATFORM_JOURNEY_ROLE_IDS,
        "Kong platform journey audienceRoleIds must match the exact six-role order",
    )
    require(
        tuple(deck.get("sourcePaths", ())) == KONG_PLATFORM_JOURNEY_SOURCE_PATHS,
        "Kong platform journey sourcePaths must match the exact canonical source order",
    )
    require(
        tuple(deck.get("sourceIds", ())) == KONG_PLATFORM_JOURNEY_SOURCE_IDS,
        "Kong platform journey sourceIds must match the exact canonical source order",
    )
    require(
        deck.get("presentationRoute") == "#/present/kong-platform-journey/0",
        "Kong platform journey presentationRoute is invalid",
    )
    require(deck.get("exitRoute") == "#/overview", "Kong platform journey exitRoute must be #/overview")
    phases = deck.get("journeyPhases")
    require(isinstance(phases, list), "Kong platform journey journeyPhases must be a list")
    observed_phases = tuple(
        (phase.get("id"), phase.get("label"), phase.get("outcome"))
        for phase in phases
        if isinstance(phase, dict)
    )
    require(
        len(observed_phases) == len(phases) and observed_phases == KONG_PLATFORM_JOURNEY_PHASES,
        "Kong platform journey phases must match the exact five-stage spine",
    )

    slides_by_key = {slide.get("key"): slide for slide in presentation if isinstance(slide, dict)}
    require(
        all(key in slides_by_key for key in KONG_PLATFORM_JOURNEY_SLIDE_KEYS),
        "Kong platform journey references a missing presentation slide",
    )
    expected_source_ids = {
        key: "docs-47-kong-enterprise-platform-strategy"
        for key in KONG_PLATFORM_JOURNEY_SLIDE_KEYS
    }
    expected_source_ids["kong-journey-options"] = "docs-44-kong-multicloud-study-roadmap"
    for key in (
        "kong-journey-migration-boundary",
        "kong-journey-migration-coexistence",
        "kong-journey-migration-waves",
    ):
        expected_source_ids[key] = MULE_MIGRATION_SOURCE_ID
    expected_source_ids["kong-journey-proof"] = "poc-readme"
    require(
        all(slides_by_key[key].get("sourceId") == expected_source_ids[key] for key in KONG_PLATFORM_JOURNEY_SLIDE_KEYS),
        "Kong platform journey slides must preserve their exact canonical source coverage",
    )

    decision_slide = slides_by_key["kong-journey-decision"]
    require(
        decision_slide.get("visual") == "kongJourneySpine",
        "Kong journey decision slide must use kongJourneySpine",
    )
    roadmap_slide = slides_by_key["kong-platform-roadmap"]
    require(
        roadmap_slide.get("visual") == "kongPlatformRoadmap",
        "Kong platform roadmap slide must use kongPlatformRoadmap",
    )

    options_slide = slides_by_key["kong-journey-options"]
    require(options_slide.get("visual") == "kongOptions", "Kong options slide must use kongOptions")
    require(
        tuple(options_slide.get("optionIds", ())) == KONG_MULTICLOUD_OPTION_IDS,
        "Kong options slide optionIds must match the exact KMC option order",
    )
    selected_slide = slides_by_key["kong-journey-selected-option"]
    require(
        selected_slide.get("visual") == "kongSelectedOption",
        "Kong selected-option slide must use kongSelectedOption",
    )
    require(
        tuple(selected_slide.get("rowIds", ())) == ("KPS-FIT-01", "KPS-FIT-02"),
        "Kong selected-option slide rowIds must be KPS-FIT-01 and KPS-FIT-02",
    )
    proof_slide = slides_by_key["kong-journey-proof"]
    require(
        proof_slide.get("visual") == "pocStatus",
        "Kong journey proof slide must use the canonical pocStatus visual",
    )
    required_migration_slides = {
        "kong-journey-migration-boundary": ("muleMigrationBoundary", None),
        "kong-journey-migration-coexistence": ("muleMigrationFigure", "MULE-3"),
        "kong-journey-migration-waves": ("muleMigrationWaves", None),
    }
    for key, (visual, figure_id) in required_migration_slides.items():
        slide = slides_by_key[key]
        require(slide.get("visual") == visual, f"slide {key} must use {visual}")
        if figure_id is not None:
            require(slide.get("figureId") == figure_id, f"slide {key} must use figure {figure_id}")

    visuals = manifest.get("visuals")
    require(isinstance(visuals, dict), "visuals must be an object")
    multicloud = visuals.get("kongMulticloud")
    require(isinstance(multicloud, dict), "visuals.kongMulticloud must be an object")
    options = multicloud.get("options")
    require(isinstance(options, list), "visuals.kongMulticloud.options must be a list")
    require(all(isinstance(option, dict) for option in options), "Kong multicloud options must be objects")
    require(
        tuple(option.get("id") for option in options) == KONG_MULTICLOUD_OPTION_IDS,
        "Kong multicloud option IDs must match the exact KMC option order",
    )
    for option in options:
        require(
            all(isinstance(option.get(field), str) and option[field].strip() for field in ("label", "placement", "role", "journeyLabel")),
            f"Kong multicloud option {option.get('id')} must retain label, placement, role, and journeyLabel evidence",
        )
    for option in options[:3]:
        require(
            all(isinstance(option.get(field), str) and option[field].strip() for field in ("journeyBoundary", "journeyRole")),
            f"primary Kong multicloud option {option.get('id')} must retain journeyBoundary and journeyRole evidence",
        )

    mule = visuals.get("muleMigration")
    require(isinstance(mule, dict), "visuals.muleMigration must be an object")
    require(mule.get("sourcePath") == MULE_MIGRATION_SOURCE_PATH, "Mule migration sourcePath is invalid")
    require(mule.get("sourceId") == MULE_MIGRATION_SOURCE_ID, "Mule migration sourceId is invalid")

    responsibilities = mule.get("responsibilities")
    require(isinstance(responsibilities, list), "Mule migration responsibilities must be a list")
    require(mule.get("responsibilityTotal") == len(MULE_RESPONSIBILITY_IDS), "Mule responsibilityTotal is invalid")
    require(all(isinstance(row, dict) for row in responsibilities), "Mule responsibilities must be objects")
    require(
        tuple(row.get("id") for row in responsibilities) == MULE_RESPONSIBILITY_IDS,
        "Mule responsibility IDs must match the exact G/F/T/O/M/B/C/R order",
    )
    for row in responsibilities:
        require(
            all(isinstance(row.get(field), str) and row[field].strip() for field in ("responsibility", "target", "evidence", "error")),
            f"Mule responsibility {row.get('id')} must retain every canonical evidence field",
        )
    responsibility_provenance = mule.get("responsibilityProvenance")
    require(isinstance(responsibility_provenance, dict), "Mule responsibility provenance must be an object")
    require(
        (
            responsibility_provenance.get("sourcePath"),
            responsibility_provenance.get("sourceId"),
            tuple(responsibility_provenance.get("sourcePaths", ())),
            tuple(responsibility_provenance.get("sourceIds", ())),
            responsibility_provenance.get("sourceHeading"),
            tuple(responsibility_provenance.get("tableColumns", ())),
        )
        == (
            MULE_MIGRATION_SOURCE_PATH,
            MULE_MIGRATION_SOURCE_ID,
            (MULE_MIGRATION_SOURCE_PATH,),
            (MULE_MIGRATION_SOURCE_ID,),
            "Mechanism analysis: decompose before selecting a target",
            ("Class", "Responsibility", "Default target", "Evidence needed", "Common error"),
        ),
        "Mule responsibility provenance must match the exact canonical table",
    )

    waves = mule.get("waves")
    require(isinstance(waves, list), "Mule migration waves must be a list")
    require(mule.get("waveTotal") == len(MULE_WAVE_IDS), "Mule waveTotal is invalid")
    require(all(isinstance(wave, dict) for wave in waves), "Mule migration waves must be objects")
    require(
        tuple(wave.get("id") for wave in waves) == MULE_WAVE_IDS,
        "Mule migration wave IDs must match the exact M0 through M5 order",
    )
    for wave in waves:
        require(
            all(isinstance(wave.get(field), str) and wave[field].strip() for field in ("label", "scope", "pattern", "entryGate", "exitGate")),
            f"Mule migration wave {wave.get('id')} must retain every canonical evidence field",
        )
    wave_provenance = mule.get("waveProvenance")
    require(isinstance(wave_provenance, dict), "Mule wave provenance must be an object")
    require(
        (
            wave_provenance.get("sourcePath"),
            wave_provenance.get("sourceId"),
            tuple(wave_provenance.get("sourcePaths", ())),
            tuple(wave_provenance.get("sourceIds", ())),
            wave_provenance.get("sourceHeading"),
            tuple(wave_provenance.get("tableColumns", ())),
        )
        == (
            MULE_MIGRATION_SOURCE_PATH,
            MULE_MIGRATION_SOURCE_ID,
            (MULE_MIGRATION_SOURCE_PATH,),
            (MULE_MIGRATION_SOURCE_ID,),
            "Migration waves",
            ("Wave", "Assumed scope", "Hard pattern intentionally included", "Entry gate", "Exit gate"),
        ),
        "Mule wave provenance must match the exact canonical table",
    )

    figures = mule.get("figures")
    require(isinstance(figures, list), "Mule migration figures must be a list")
    require(all(isinstance(figure, dict) for figure in figures), "Mule migration figures must be objects")
    require(
        tuple(figure.get("figureId") for figure in figures) == tuple(MULE_FIGURE_HEADINGS),
        "Mule figure IDs must match the exact MULE-2/MULE-3/MULE-6 order",
    )
    for figure in figures:
        figure_id = figure["figureId"]
        require(
            all(isinstance(figure.get(field), str) and figure[field].strip() for field in ("title", "mermaid")),
            f"Mule figure {figure_id} must retain title and Mermaid source",
        )
        provenance = figure.get("provenance")
        require(isinstance(provenance, dict), f"Mule figure {figure_id} provenance must be an object")
        require(
            (
                provenance.get("sourcePath"),
                provenance.get("sourceId"),
                tuple(provenance.get("sourcePaths", ())),
                tuple(provenance.get("sourceIds", ())),
                provenance.get("sourceHeading"),
                provenance.get("figureId"),
            )
            == (
                MULE_MIGRATION_SOURCE_PATH,
                MULE_MIGRATION_SOURCE_ID,
                (MULE_MIGRATION_SOURCE_PATH,),
                (MULE_MIGRATION_SOURCE_ID,),
                MULE_FIGURE_HEADINGS[figure_id],
                figure_id,
            ),
            f"Mule figure {figure_id} provenance must match its exact canonical figure",
        )


def publishable_source_inventory() -> set[str]:
    """Enumerate canonical publishable sources independently of the manifest."""
    inventory: set[str] = set()
    for source in repository_candidate_paths():
        relative = source.relative_to(ROOT)
        if not relative.parts or relative.parts[0] not in CONTENT_ROOTS:
            continue
        if any(part.startswith(".") for part in relative.parts):
            continue
        if source.suffix.lower() in PUBLISHABLE_EXTENSIONS or source.name == "Dockerfile":
            inventory.add(relative.as_posix())
    return inventory


def deterministic_timestamp(revision: str) -> str:
    epoch_value = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch_value is None:
        epoch_value = run_git("show", "-s", "--format=%ct", revision)
    require(bool(re.fullmatch(r"\d+", epoch_value)), f"SOURCE_DATE_EPOCH is invalid: {epoch_value!r}")
    epoch = int(epoch_value)
    try:
        return datetime.fromtimestamp(epoch, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    except (OverflowError, OSError, ValueError) as exc:
        raise ValidationError(f"SOURCE_DATE_EPOCH is outside the supported timestamp range: {epoch_value!r}") from exc


def validate_metadata(manifest: dict[str, Any], expected_revision: str | None, require_clean: bool) -> None:
    require(manifest.get("schemaVersion") == SCHEMA_VERSION, f"schemaVersion must be {SCHEMA_VERSION}")
    revision = manifest.get("sourceRevision")
    require(isinstance(revision, str) and bool(REVISION_PATTERN.fullmatch(revision)), "sourceRevision must be a full lowercase Git object ID")

    head = run_git("rev-parse", "--verify", "HEAD^{commit}")
    run_git("cat-file", "-e", f"{revision}^{{commit}}")
    status = run_git("status", "--porcelain=v1", "--untracked-files=all")
    expected_dirty = bool(status) or revision != head or not raw_tracked_bytes_match(revision)
    require(type(manifest.get("sourceDirty")) is bool, "sourceDirty must be a boolean")
    require(manifest["sourceDirty"] == expected_dirty, "sourceDirty does not match the checkout, revision, and worktree state")

    if expected_revision:
        resolved_expected = run_git("rev-parse", "--verify", f"{expected_revision}^{{commit}}")
        require(revision == resolved_expected, f"manifest revision {revision} does not match expected revision {resolved_expected}")
    if require_clean:
        require(not manifest["sourceDirty"], "a clean publication was required but sourceDirty is true")

    expected_generated_at = deterministic_timestamp(revision)
    require(
        manifest.get("generatedAt") == expected_generated_at,
        f"generatedAt must be the reproducible timestamp {expected_generated_at}",
    )
    generator = manifest.get("generator")
    require(isinstance(generator, dict), "generator must contain path and SHA-256 provenance")
    require(generator.get("path") == GENERATOR_PATH, f"generator.path must be {GENERATOR_PATH}")
    generator_hash = generator.get("sha256")
    require(isinstance(generator_hash, str) and bool(SHA256_PATTERN.fullmatch(generator_hash)), "generator.sha256 is invalid")
    require(generator_hash == sha256_file(ROOT / GENERATOR_PATH), "generator SHA-256 does not match scripts/build_site.py")


def validate_items(manifest: dict[str, Any], output: Path) -> tuple[dict[str, dict[str, Any]], set[str]]:
    items = manifest.get("items")
    require(isinstance(items, list) and bool(items), "items must be a non-empty list")
    require(all(isinstance(item, dict) for item in items), "every item must be an object")

    ids = [item.get("id") for item in items]
    paths = [item.get("path") for item in items]
    content_urls = [item.get("contentUrl") for item in items]
    routes = [item.get("route") for item in items]
    for values, label in ((ids, "item IDs"), (paths, "item paths"), (content_urls, "item content URLs"), (routes, "item routes")):
        require(all(isinstance(value, str) and value for value in values), f"{label} must be non-empty strings")
        unique(values, label)
    expected_sources = publishable_source_inventory()
    require(set(paths) == expected_sources, "manifest items do not equal the independently enumerated publishable source set")

    by_id: dict[str, dict[str, Any]] = {}
    expected_copies: set[str] = set()
    for item in items:
        item_id = item["id"]
        relative = safe_relative(item["path"], f"item {item_id} path")
        content_relative = safe_relative(item["contentUrl"], f"item {item_id} contentUrl")
        expected_content = PurePosixPath("content") / relative
        require(content_relative == expected_content, f"item {item_id} contentUrl must be content/{relative}")
        require(item["route"] == f"#/doc/{item_id}", f"item {item_id} has an invalid document route")

        source = under(ROOT, relative, f"item {item_id} source")
        copy = under(output, content_relative, f"item {item_id} copy")
        require(source.is_file(), f"item {item_id} source is missing: {relative}")
        require(copy.is_file(), f"item {item_id} generated copy is missing: {content_relative}")
        digest = item.get("sha256")
        require(isinstance(digest, str) and bool(SHA256_PATTERN.fullmatch(digest)), f"item {item_id} SHA-256 is invalid")
        require(sha256_file(source) == digest, f"item {item_id} source SHA-256 does not match the manifest")
        require(sha256_file(copy) == digest, f"item {item_id} generated copy SHA-256 does not match its source")
        require(item.get("size") == source.stat().st_size == copy.stat().st_size, f"item {item_id} size metadata is invalid")
        by_id[item_id] = item
        expected_copies.add(content_relative.as_posix())

    content_root = output / "content"
    actual_copies = {
        path.relative_to(output).as_posix()
        for path in content_root.rglob("*")
        if path.is_file()
    }
    require(actual_copies == expected_copies, "generated content files and manifest items are not a one-to-one set")
    return by_id, set(routes)


def validate_assets(manifest: dict[str, Any], output: Path) -> None:
    assets = manifest.get("assets")
    require(isinstance(assets, dict), "assets must be an object keyed by generated path")
    source_asset_paths = {
        path.relative_to(ROOT / "site").as_posix()
        for path in repository_candidate_paths()
        if path.relative_to(ROOT).parts[:1] == ("site",)
    }
    expected_asset_paths = source_asset_paths | {"404.html"}
    require(REQUIRED_ASSET_PATHS.issubset(expected_asset_paths), "required site asset sources are missing")
    require(set(assets) == expected_asset_paths, "asset digest set does not match the complete site source set")

    for relative_value in sorted(expected_asset_paths):
        relative = safe_relative(relative_value, "asset path")
        generated = under(output, relative, f"asset {relative_value}")
        source_relative = PurePosixPath("index.html") if relative_value == "404.html" else relative
        source = under(ROOT / "site", source_relative, f"asset {relative_value} source")
        require(source.is_file() and generated.is_file(), f"asset {relative_value} is missing")
        metadata = assets[relative_value]
        require(isinstance(metadata, dict), f"asset {relative_value} metadata must be an object")
        digest = metadata.get("sha256")
        require(isinstance(digest, str) and bool(SHA256_PATTERN.fullmatch(digest)), f"asset {relative_value} SHA-256 is invalid")
        require(sha256_file(source) == digest, f"asset {relative_value} source SHA-256 does not match the manifest")
        require(sha256_file(generated) == digest, f"asset {relative_value} generated SHA-256 does not match the source")
        require(metadata.get("size") == source.stat().st_size == generated.stat().st_size, f"asset {relative_value} size is invalid")

    for source in sorted(
        path for path in repository_candidate_paths()
        if path.relative_to(ROOT).parts[:1] == ("site",)
    ):
        relative = source.relative_to(ROOT / "site")
        generated = output / relative
        require(generated.is_file(), f"site source was not copied: {relative.as_posix()}")
        require(sha256_file(source) == sha256_file(generated), f"site source copy differs: {relative.as_posix()}")
    require((output / ".nojekyll").is_file(), "generated site is missing .nojekyll")
    index_text = (ROOT / "site" / "index.html").read_text(encoding="utf-8")
    parser = ScriptSourceParser()
    parser.feed(index_text)
    parser.close()
    require(bool(parser.scripts), "site index must declare its runtime scripts")
    external_seen: set[str] = set()
    local_seen: set[str] = set()
    for raw_attrs in parser.scripts:
        names = [name.lower() for name, _ in raw_attrs]
        require(len(names) == len(set(names)), "script tag contains duplicate attributes")
        attrs = {name.lower(): value for name, value in raw_attrs}
        source = attrs.get("src")
        require(isinstance(source, str) and bool(source), "inline or source-less scripts are not permitted")
        if source.startswith("https://"):
            expected_integrity = ALLOWED_EXTERNAL_SCRIPTS.get(source)
            require(expected_integrity is not None, "external script is not in the exact versioned runtime allowlist")
            require(source not in external_seen, "external runtime script is declared more than once")
            require(attrs.get("integrity") == expected_integrity, "external script Subresource Integrity differs from the allowlist")
            require(attrs.get("crossorigin", "").lower() == "anonymous", "every external script must use anonymous CORS for Subresource Integrity")
            external_seen.add(source)
        else:
            require(source in REQUIRED_LOCAL_SCRIPTS, "local script source is outside the required site asset set")
            require(source not in local_seen, "local runtime script is declared more than once")
            require("integrity" not in attrs and "crossorigin" not in attrs, "local scripts must use manifest provenance rather than external SRI attributes")
            local_seen.add(source)
    require(external_seen == set(ALLOWED_EXTERNAL_SCRIPTS), "site index external runtime set differs from the exact allowlist")
    require(local_seen == REQUIRED_LOCAL_SCRIPTS, "site index local runtime set is incomplete or duplicated")


def validate_output_inventory(manifest: dict[str, Any], output: Path) -> None:
    """Require every generated file to belong to the declared site artifact."""

    require(output.is_dir() and not output.is_symlink(), "generated output root must be a regular directory")
    expected = {
        "content-manifest.json",
        ".nojekyll",
        OUTPUT_SENTINEL,
        *manifest["assets"].keys(),
        *(item["contentUrl"] for item in manifest["items"]),
    }
    actual: set[str] = set()
    for path in output.rglob("*"):
        relative = path.relative_to(output).as_posix()
        require(not path.is_symlink(), "generated output contains a symlink")
        if path.is_dir():
            continue
        require(path.is_file(), "generated output contains a non-regular path")
        actual.add(relative)

    require(actual == expected, "generated output contains undeclared or missing files")
    sentinel = output / OUTPUT_SENTINEL
    require(sentinel.is_file(), "generated output ownership sentinel is missing")
    try:
        sentinel_bytes = sentinel.read_bytes()
        nojekyll_size = (output / ".nojekyll").stat().st_size
    except OSError as exc:
        raise ValidationError("generated output metadata cannot be read") from exc
    require(
        sentinel_bytes == OUTPUT_SENTINEL_VALUE.encode("utf-8"),
        "generated output ownership sentinel is invalid",
    )
    require(nojekyll_size == 0, ".nojekyll must be empty")


def validate_routes_and_audiences(
    manifest: dict[str, Any],
    by_id: dict[str, dict[str, Any]],
    document_routes: set[str],
) -> None:
    presentation = manifest.get("presentation")
    require(isinstance(presentation, list) and bool(presentation), "presentation must be a non-empty list")
    require(all(isinstance(slide, dict) for slide in presentation), "every presentation slide must be an object")
    slide_keys = [slide.get("key") for slide in presentation]
    require(all(isinstance(key, str) and key for key in slide_keys), "presentation keys must be non-empty strings")
    unique(slide_keys, "presentation keys")
    indices = [slide.get("index") for slide in presentation]
    require(indices == list(range(len(presentation))), "presentation indices must be unique and contiguous from zero")
    for slide in presentation:
        require(slide.get("sourceId") in by_id, f"slide {slide.get('key')} references an unknown sourceId")
    validate_poc_projection(manifest)
    validate_kong_platform_fit_slides(manifest, presentation)

    all_routes = set(document_routes)
    generic_presentation_routes = {f"#/present/{index}" for index in range(len(presentation))}
    require(not all_routes.intersection(generic_presentation_routes), "document and presentation routes collide")
    all_routes.update(generic_presentation_routes)

    audiences = manifest.get("audiences")
    require(isinstance(audiences, list) and bool(audiences), "audiences must be a non-empty list")
    require(all(isinstance(audience, dict) for audience in audiences), "every audience must be an object")
    audience_ids = [audience.get("id") for audience in audiences]
    require(all(isinstance(audience_id, str) and audience_id for audience_id in audience_ids), "audience IDs must be non-empty strings")
    unique(audience_ids, "audience IDs")

    path_to_id = {item["path"]: item_id for item_id, item in by_id.items()}

    def validate_sources(subject: dict[str, Any], label: str, *, require_nonempty: bool = False) -> list[str]:
        source_paths = subject.get("sourcePaths")
        source_ids = subject.get("sourceIds")
        require(isinstance(source_paths, list) and isinstance(source_ids, list), f"{label} sources must be lists")
        if require_nonempty:
            require(bool(source_paths), f"{label} must declare at least one source")
        require(all(isinstance(path, str) for path in source_paths), f"{label} sourcePaths are invalid")
        require(all(isinstance(item_id, str) for item_id in source_ids), f"{label} sourceIds are invalid")
        unique(source_paths, f"{label} sourcePaths")
        unique(source_ids, f"{label} sourceIds")
        expected_source_ids = [path_to_id.get(path) for path in source_paths]
        require(None not in expected_source_ids, f"{label} references an unknown source path")
        require(source_ids == expected_source_ids, f"{label} source IDs do not align with source paths")
        return source_ids

    for audience in audiences:
        audience_id = audience["id"]
        validate_sources(audience, f"audience {audience_id}")

        selected_slides = audience.get("presentationSlides")
        require(isinstance(selected_slides, list) and bool(selected_slides), f"audience {audience_id} has no presentation slides")
        require(all(isinstance(key, str) for key in selected_slides), f"audience {audience_id} presentation slides are invalid")
        require(
            not any(key in REMOVED_KONG_PLATFORM_FIT_SLIDE_KEYS for key in selected_slides),
            f"audience {audience_id} retains a removed Kong platform fit slide",
        )
        require(all(key in slide_keys for key in selected_slides), f"audience {audience_id} references an unknown slide")
        unique(selected_slides, f"audience {audience_id} presentation slides")

        expected_entry_route = f"#/present/{audience_id}/0"
        require(audience.get("presentationRoute") == expected_entry_route, f"audience {audience_id} presentationRoute is invalid")
        audience_routes = {f"#/present/{audience_id}/{index}" for index in range(len(selected_slides))}
        audience_routes.add(f"#/audiences/{audience_id}")
        require(not all_routes.intersection(audience_routes), f"audience {audience_id} routes collide with another route")
        all_routes.update(audience_routes)

        recommended = audience.get("recommendedRoute")
        require(isinstance(recommended, str), f"audience {audience_id} recommendedRoute is invalid")
        normalized = recommended.split("?", 1)[0]
        require(normalized in STATIC_ROUTES or normalized in document_routes, f"audience {audience_id} recommendedRoute is unknown")

    decks = manifest.get("presentationDecks")
    require(isinstance(decks, list) and bool(decks), "presentationDecks must be a non-empty list")
    require(all(isinstance(deck, dict) for deck in decks), "every presentation deck must be an object")
    deck_ids = [deck.get("id") for deck in decks]
    require(all(isinstance(deck_id, str) and deck_id for deck_id in deck_ids), "presentation deck IDs must be non-empty strings")
    unique(deck_ids, "presentation deck IDs")
    require(not set(deck_ids).intersection(audience_ids), "presentation deck IDs must not collide with audience IDs")

    for deck in decks:
        deck_id = deck["id"]
        source_ids = validate_sources(deck, f"presentation deck {deck_id}", require_nonempty=True)

        selected_slides = deck.get("presentationSlides")
        require(isinstance(selected_slides, list) and bool(selected_slides), f"presentation deck {deck_id} has no presentation slides")
        require(all(isinstance(key, str) for key in selected_slides), f"presentation deck {deck_id} presentation slides are invalid")
        require(
            not any(key in REMOVED_KONG_PLATFORM_FIT_SLIDE_KEYS for key in selected_slides),
            f"presentation deck {deck_id} retains a removed Kong platform fit slide",
        )
        require(all(key in slide_keys for key in selected_slides), f"presentation deck {deck_id} references an unknown slide")
        unique(selected_slides, f"presentation deck {deck_id} presentation slides")
        require(
            type(deck.get("slideTotal")) is int and deck["slideTotal"] == len(selected_slides),
            f"presentation deck {deck_id} slideTotal must equal its presentation slide count",
        )
        selected_source_ids = {
            slide["sourceId"] for slide in presentation if slide["key"] in selected_slides
        }
        require(
            selected_source_ids.issubset(set(source_ids)),
            f"presentation deck {deck_id} sources do not cover its selected slides",
        )

        role_ids = deck.get("audienceRoleIds")
        require(isinstance(role_ids, list) and bool(role_ids), f"presentation deck {deck_id} audienceRoleIds must be a non-empty list")
        require(
            all(isinstance(role_id, str) and role_id in audience_ids for role_id in role_ids),
            f"presentation deck {deck_id} references an unknown audience role",
        )
        unique(role_ids, f"presentation deck {deck_id} audienceRoleIds")

        expected_entry_route = f"#/present/{deck_id}/0"
        require(deck.get("presentationRoute") == expected_entry_route, f"presentation deck {deck_id} presentationRoute is invalid")
        deck_routes = {f"#/present/{deck_id}/{index}" for index in range(len(selected_slides))}
        require(not all_routes.intersection(deck_routes), f"presentation deck {deck_id} routes collide with another route")
        all_routes.update(deck_routes)

        exit_route = deck.get("exitRoute")
        require(isinstance(exit_route, str), f"presentation deck {deck_id} exitRoute is invalid")
        normalized_exit = exit_route.split("?", 1)[0]
        require(
            normalized_exit in STATIC_ROUTES or normalized_exit in document_routes,
            f"presentation deck {deck_id} exitRoute is unknown",
        )


def validate(output: Path, expected_revision: str | None, require_clean: bool) -> dict[str, Any]:
    require(output.is_dir() and not output.is_symlink(), "generated output root must be a regular directory")
    manifest_path = output / "content-manifest.json"
    require(manifest_path.is_file(), f"site manifest is missing: {manifest_path}")
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValidationError(f"site manifest is not valid UTF-8 JSON: {exc}") from exc
    require(isinstance(manifest, dict), "site manifest root must be an object")
    validate_metadata(manifest, expected_revision, require_clean)
    by_id, document_routes = validate_items(manifest, output)
    validate_assets(manifest, output)
    validate_output_inventory(manifest, output)
    validate_routes_and_audiences(manifest, by_id, document_routes)
    validate_kong_platform_journey(manifest, manifest["presentation"])
    return manifest


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "_site", help="Generated site directory")
    parser.add_argument(
        "--expected-revision",
        default=os.environ.get("SOURCE_REVISION") or os.environ.get("GITHUB_SHA"),
        help="Revision the manifest must identify (defaults to SOURCE_REVISION, then GITHUB_SHA)",
    )
    parser.add_argument("--require-clean", action="store_true", help="Reject a manifest built from a dirty or mismatched checkout")
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    try:
        # Preserve the lexical output path so validate_output_inventory can
        # reject a symlinked root instead of silently validating its target.
        manifest = validate(output, args.expected_revision, args.require_clean)
    except ValidationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    deck_count = len(manifest["presentationDecks"])
    deck_label = "named deck" if deck_count == 1 else "named decks"
    print(
        "OK: site manifest validates "
        f"{len(manifest['items'])} source copies, {len(manifest['assets'])} assets, "
        f"{len(manifest['audiences'])} audiences, {deck_count} {deck_label}, "
        f"and revision {manifest['sourceRevision']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
